/* ==================== 新媒体爆款工作台 - 数据层 ====================
   数据来源说明：
   - 爆款视频数据来源于新榜、公开报道、平台公开信息的人工整理
   - 抖音/快手/小红书/B站等平台无公开搜索API，无法自动实时爬取
   - 如需更新爆款库，可通过「内容更新中心」手动添加，或联系开发者补充
   ==================================================================== */

/* 平台配置 */
const PLATFORMS = {
  douyin:    { name: '抖音',     color: '#000000', bg: '#1a1a1a', icon: '🎵' },
  kuaishou:  { name: '快手',     color: '#ff6b35', bg: '#2a1810', icon: '⚡' },
  xhs:       { name: '小红书',   color: '#ff2442', bg: '#2a0f15', icon: '📕' },
  bilibili:  { name: 'B站',      color: '#00a1d6', bg: '#0a1e2a', icon: '📺' },
  wechat:    { name: '视频号',   color: '#07c160', bg: '#0a2418', icon: '💬' },
  youtube:   { name: 'YouTube', color: '#ff0000', bg: '#2a0a0a', icon: '▶' },
  tiktok:    { name: 'TikTok',  color: '#010101', bg: '#1a1a1a', icon: '🎼' },
  toutiao:   { name: '今日头条', color: '#ff0000', bg: '#2a0a0a', icon: '📰' }
};

/* 默认分类 */
const DEFAULT_CATEGORIES = [
  { id: 'aigc',       name: 'AIGC培训',      color: '#7c6cff', icon: '🤖', desc: 'AI生成内容培训、AI工具教学、AI创业方向、AI爆款拆解' },
  { id: 'aigc_create',name: 'AIGC爆款作品',   color: '#9b59f0', icon: '🎬', desc: 'AI生成的爆款短片、AI转场、AI创意视频作品' },
  { id: 'ecommerce', name: '电商带货',       color: '#ff6b35', icon: '🛒', desc: '直播带货、短视频带货、选品策略' },
  { id: 'knowledge', name: '知识付费',       color: '#00c896', icon: '📚', desc: '课程推广、付费社群、训练营' },
  { id: 'brand',     name: '品牌营销',       color: '#ff2442', icon: '🎯', desc: '品牌种草、营销事件、IP打造' },
  { id: 'drama',     name: '剧情短剧',       color: '#ffa500', icon: '🎭', desc: '微短剧、连载剧情、情感故事' },
  { id: 'local',     name: '本地生活',       color: '#4facfe', icon: '📍', desc: '探店、本地团购、同城推广' },
  { id: 'personal',  name: '个人IP',         color: '#f5576c', icon: '⭐', desc: '个人品牌、人设打造、粉丝运营' },
  { id: 'tool',      name: '工具/软件',      color: '#2dca73', icon: '🔧', desc: '软件推荐、效率工具、AI工具' }
];

/* 爆款视频数据 - 来源于新榜、公开报道、平台公开信息的整理 */
const DEMO_VIDEOS = [
  /* ======== AIGC爆款作品（真实全网数据） ======== */
  {
    id: 'real001',
    title: '《纸手机》清明催泪AI短片：15元纸手机打给去世的奶奶',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: 'WAI-你听 & FOS',
    authorFollowers: 850000,
    views: 230000000,
    likes: 13650000,
    comments: 890000,
    shares: 1200000,
    duration: 180,
    date: '2026-04-03',
    tags: ['AI短片', '情感共鸣', '清明节', '影视级', '全网刷屏', '央视转发'],
    script: '一个小男孩攒了15块钱，买了一部纸手机，想给去世的奶奶打最后一通视频电话。细腻的情感，影视级的画面，AI让不可能的对话变成了可能。全网曝光量2.3亿，被央视新闻、人民日报等主流媒体转发。网友评价：用最没人味的AI，拍出了今年清明最有人味的短片。这才是AI的意义。',
    videoUrl: '',
    isReal: true,
    source: '新榜数据 2026上半年AI爆款盘点'
  },
  {
    id: 'real002',
    title: '《钟馗嫁妹》AI短剧：48小时播放破4000万',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: '万梦生团队',
    authorFollowers: 320000,
    views: 40000000,
    likes: 3100000,
    comments: 156000,
    shares: 280000,
    duration: 560,
    date: '2026-06-15',
    tags: ['AI短剧', '民俗怪谈', '闽南语', '电影质感', '草根团队', '低成本'],
    script: '3个门外汉，5000块钱，2周时间，用AI拍了一部不到10分钟的短片。把钟馗从捉鬼天师，变成了一个有血有肉的凡人兄长。画面有电影质感，剧情节奏连贯，还有部分闽南语对白。48小时播放破4000万，点赞超300万。队长赵万权初中毕业干过搬运工，后期阿生以前是体育老师，视效导演瓜铭做过灯光师。他们用即梦AI造出了整个剧组。',
    videoUrl: '',
    isReal: true,
    source: '新榜报道 2026年6月'
  },
  {
    id: 'real003',
    title: '《早餐奶奶》AI致敬短片：抖音播放量2.5亿',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: '旧梦留声机',
    authorFollowers: 680000,
    views: 250000000,
    likes: 15090000,
    comments: 620000,
    shares: 980000,
    duration: 240,
    date: '2026-05-20',
    tags: ['AI短片', '致敬', '人间温情', '川渝口音', '早餐奶奶', '抖音第一'],
    script: '以此致敬已故的浙江衢州"早餐奶奶"毛师花。出于对这些吃不饱饭的山区贫困孩子的怜爱，毛师花坚持二十多年在小学门口摆早餐摊，风雨无阻，每份早餐只卖5毛钱，从未涨价。细腻的光影、富有年代感的画面和颇具地方特色的川渝口音，让这条AI视频有了更强的现实代入感。抖音播放量2.5亿，获赞1509万，是抖音2026上半年播放量最高的AIGC短片。',
    videoUrl: '',
    isReal: true,
    source: '新榜数据 2026上半年AI爆款盘点'
  },
  {
    id: 'real004',
    title: '《他守了家国一辈子》AI转场：播放量2.95亿获赞1867万',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: '涵堡包',
    authorFollowers: 1200000,
    views: 295000000,
    likes: 18670000,
    comments: 890000,
    shares: 1500000,
    duration: 90,
    date: '2026-04-15',
    tags: ['AI转场', '情感共鸣', '家国情怀', '婚礼墓地转场', '小家大家', '抖音破亿'],
    script: '视频开头是一位老人带着白菊来到一座墓前，在鞠躬悼念时，画面借助AI转场成一位新娘与年轻战士拜堂成亲的情景。婚礼与墓地的转场，是小家与大家的取舍。他守了家国一辈子，我守着他的回忆一辈子，这一拜成了永远。抖音播放量达2.95亿，获赞1867万。',
    videoUrl: '',
    isReal: true,
    source: '新榜数据 2026上半年AI爆款盘点'
  },
  {
    id: 'real005',
    title: '《银包金》AI情感短片：抖音播放量1.15亿',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: '拾光故事馆',
    authorFollowers: 520000,
    views: 115000000,
    likes: 6600000,
    comments: 320000,
    shares: 450000,
    duration: 200,
    date: '2026-05-10',
    tags: ['AI短片', '情感故事', '金银首饰', '中式温情', '第一人称', '抖音破亿'],
    script: '一对年轻男女因为金包银、银包金首饰而不欢而散的情感故事。第一人称POV视角，还原真实情感故事。抖音播放量1.15亿，获赞660万。中式温情故事是AI内容赛道的持续热门方向。',
    videoUrl: '',
    isReal: true,
    source: '新榜数据 2026上半年AI爆款盘点'
  },
  {
    id: 'real006',
    title: '建鹏AI转场变装：单条获赞1365万转发111万',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: '建鹏',
    authorFollowers: 2100000,
    views: 180000000,
    likes: 13650000,
    comments: 450000,
    shares: 1110000,
    duration: 11,
    date: '2026-03-11',
    tags: ['AI转场', '变装', '创意视觉', '世界和平', '子弹鲜花', '抖音百万赞'],
    script: '完全由AI生成的11秒转场视频，通过子弹、鲜花、和平鸽、孩子等元素，表达了对世界和平的期待。一位网友在评论区留言：子弹还要飞多久，才能变成和平鸽。建鹏是典型的转场变装博主，擅长将有趣的创意、饱满的情绪转换成极致的视觉轰炸，AI则让他实现了极低成本的"上天入地"。今年以来累计产出12条百万赞以上AI视频，累计涨粉73万。',
    videoUrl: '',
    isReal: true,
    source: '新榜报道 2026年4月'
  },
  {
    id: 'real007',
    title: '《零号档案》AI科幻系列：播放量突破5700万涨粉96万',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: '白袋子',
    authorFollowers: 960000,
    views: 57000000,
    likes: 4200000,
    comments: 180000,
    shares: 230000,
    duration: 300,
    date: '2026-06-20',
    tags: ['AI科幻', '系列连载', '原创世界观', '门', '涨粉', '追更习惯'],
    script: '打造的原创AI短片《零号档案》系列，构建了以"门"为核心设定的科幻世界。通过连载系列和宏大的世界观设定，来培养粉丝的追更习惯。单系列播放量突破5700万，成功带动了96万的粉丝增长。内容系列化和长线叙事是持续涨粉的关键。',
    videoUrl: '',
    isReal: true,
    source: '新榜数据 2026上半年AI爆款盘点'
  },
  {
    id: 'real008',
    title: '《丧尸清道夫》AI末日废土短片：获好莱坞邀约',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: 'MxShell',
    authorFollowers: 680000,
    views: 32000000,
    likes: 2800000,
    comments: 95000,
    shares: 120000,
    duration: 180,
    date: '2026-05-25',
    tags: ['AI短片', '末日废土', '好莱坞', '个人风格', '影视级', '涨粉'],
    script: '凭借AI短片《丧尸清道夫》独特的末日废土风格，在国内外平台引发广泛关注，并获得了好莱坞制片人的关注和邀约，抖音账号迅速涨粉68万。带有强烈的个人风格和影视级质感。',
    videoUrl: '',
    isReal: true,
    source: '新榜数据 2026上半年AI爆款盘点'
  },
  {
    id: 'real009',
    title: '《天枢防线》《南天门计划》AI科幻短片系列',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: 'AIGC十三',
    authorFollowers: 520000,
    views: 28000000,
    likes: 2100000,
    comments: 78000,
    shares: 95000,
    duration: 280,
    date: '2026-06-10',
    tags: ['AI科幻', '系列连载', '南天门', '持续更新', '涨粉52万'],
    script: '持续更新《天枢防线》《南天门计划》等系列短片，抖音半年涨粉52万。说明这些作者具备持续打造AI爆款的能力。',
    videoUrl: '',
    isReal: true,
    source: '新榜数据 2026上半年AI爆款盘点'
  },
  {
    id: 'real010',
    title: '《北镜行者》AI赛博朋克短片：20天打造',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: '命比梦长',
    authorFollowers: 280000,
    views: 15000000,
    likes: 1200000,
    comments: 42000,
    shares: 58000,
    duration: 320,
    date: '2026-04-20',
    tags: ['AI短片', '赛博朋克', '20天制作', '电影质感', '团队合作'],
    script: '命比梦长和几位朋友一起，仅用20天时间打造出了一部赛博朋克短片。画面有极为炫酷、媲美电影的质感。',
    videoUrl: '',
    isReal: true,
    source: '新榜报道 2026年4月'
  },

  /* ======== AIGC培训教学类（真实全网数据） ======== */
  {
    id: 'real011',
    title: '用DeepSeek做AI养生视频，条条10w+（保姆级教程）',
    platform: 'toutiao',
    categoryId: 'aigc',
    author: '机心见道',
    authorFollowers: 150000,
    views: 200000,
    likes: 28000,
    comments: 3200,
    shares: 8500,
    duration: 300,
    date: '2026-06-27',
    tags: ['DeepSeek', 'AI养生', '保姆级教程', '零基础', '免费工具', '流水线生产'],
    script: '说实话，你是不是也刷到过那种账号——AI生成的仙风道骨老中医，配上一段养生语录，背景是高山流水、云雾缭绕，点赞动不动就几万、十几万？我花了一个周末，用DeepSeek配合几个免费工具，一口气做出了7条视频。发出去之后，数据最好的那条已经破了20万播放，全程没花一分钱。第一步：让DeepSeek给你当"文案工厂"，提示词直接抄。第二步：用即梦AI生成"仙风道骨老中医"数字人。第三步：剪映AI配音。三步搞定一条爆款。',
    videoUrl: '',
    isReal: true,
    source: '今日头条 2026年6月'
  },
  {
    id: 'real012',
    title: '用AI做古人怼人视频，超火"回答我"保姆级教程',
    platform: 'douyin',
    categoryId: 'aigc',
    author: 'AI教程达人',
    authorFollowers: 320000,
    views: 26000000,
    likes: 700000,
    comments: 45000,
    shares: 120000,
    duration: 180,
    date: '2026-05-15',
    tags: ['AI古人', '怼人', '回答我', '即梦AI', 'DeepSeek', '爆款复制', '教程'],
    script: '近期，李时珍怒怼"奶茶续命"、诸葛亮吐槽"甲方改稿"、陶渊明反驳"躺平质疑"的视频在各大平台爆火，单条视频点赞超70万，合计播放量破2600万。核心魅力在于三重反差：古人儒雅人设与暴躁吐槽的性格反差、历史典故与现代梗的时空反差、"回答我！Look in my eyes!Tell me why?baby why?"的魔性句式与严肃历史人物的风格反差。第一步：用即梦AI生成原创古人形象。第二步：用DeepSeek写"怼人"文案。第三步：AI配音+剪映合成。',
    videoUrl: '',
    isReal: true,
    source: 'QQ新闻 2026年5月'
  },
  {
    id: 'real013',
    title: '小白5分钟做出29.9万赞！AI水果狗血剧爆款复制法',
    platform: 'douyin',
    categoryId: 'aigc',
    author: 'AI爆款拆解',
    authorFollowers: 280000,
    views: 8500000,
    likes: 299000,
    comments: 18000,
    shares: 42000,
    duration: 300,
    date: '2026-04-29',
    tags: ['AI拟人化', '水果狗血剧', '5分钟', '零基础', '爆款复制', '保姆级'],
    script: '单条视频爆赞29.9万！用AI做水果狗血剧，5分钟教你复刻同款。这种视频之所以爆火，核心就是：AI降本+成熟模板+情绪爽点。先把香蕉、草莓这些水果拟人化，然后直接套用恋综或者复仇的经典套路，一分钟一个高密度反转，全程强冲突。凌晨三点，我闺蜜突然给我弹了条语音：你看我抖音！那个用AI做的榴莲总裁视频，爆了！29.9万赞，就在她发布后的第18个小时。课程内容：1.爆款案例展示 2.生成分镜脚本 3.生成参考图 4.生成视频 5.视频剪辑。',
    videoUrl: '',
    isReal: true,
    source: '58课堂 2026年4月'
  },
  {
    id: 'real014',
    title: '不拍不剪不写文案照样做出百万播放：AI人生副本短视频',
    platform: 'toutiao',
    categoryId: 'aigc',
    author: 'AI创作拆解',
    authorFollowers: 190000,
    views: 5000000,
    likes: 85000,
    comments: 6200,
    shares: 15000,
    duration: 240,
    date: '2026-06-20',
    tags: ['AI人生副本', '第一人称叙事', '沉浸式', 'AI配音', 'AI配图', '零基础'],
    script: '画面是一张张略带颗粒感的图，一个低沉的声音缓缓开口：今天，你要体验的人生副本是——送一天外卖。然后你就这么一直看了下去，3分钟没快进没划走。这类视频单条播放动辄几十万到几百万，完播率高得离谱。它不需要你会拍摄、不需要你会剪辑、甚至不需要你会写文案。从头到尾AI帮你把活全干了。5步出片：写剧本→拆分镜→生成图片→AI配音→剪映合成。第一次做全程大概1小时，熟练之后30分钟就能出一条。',
    videoUrl: '',
    isReal: true,
    source: '今日头条 2026年6月'
  },
  {
    id: 'real015',
    title: 'Transformer论文逐段精读【论文精读】',
    platform: 'bilibili',
    categoryId: 'aigc',
    author: '跟李沐学AI',
    authorFollowers: 1132000,
    views: 1755000,
    likes: 43000,
    comments: 8900,
    shares: 12000,
    duration: 3600,
    date: '2026-01-15',
    tags: ['Transformer', '论文精读', '深度学习', 'AI基础', '李沐', 'B站经典'],
    script: '李沐的Transformer论文逐段精读，B站AI学习必看经典。113.2万粉丝，60+篇论文精读，论文精读天花板，1361万合集播放。适合所有想深入理解大语言模型原理的学习者。从Attention机制到Self-Attention，从位置编码到Multi-Head Attention，逐段拆解，通俗易懂。',
    videoUrl: 'https://www.bilibili.com/video/BV1pu411g',
    isReal: true,
    source: 'B站公开数据 2026年'
  },
  {
    id: 'real016',
    title: '李宏毅机器学习深度学习系列课程全集',
    platform: 'bilibili',
    categoryId: 'aigc',
    author: '李宏毅深度学习课堂',
    authorFollowers: 850000,
    views: 933000,
    likes: 26000,
    comments: 6500,
    shares: 8900,
    duration: 7200,
    date: '2026-02-01',
    tags: ['李宏毅', '机器学习', '深度学习', '入门课程', '公认最好', '2025版'],
    script: '公认体验感最好的入门课程。2025版李宏毅机器学习深度学习系列课程全集。93.3万播放，2.6万收藏。从基础概念到最新的大模型技术，系统全面，适合零基础入门。李宏毅教授的课程以幽默风趣、深入浅出著称，是B站AI学习的标杆内容。',
    videoUrl: '',
    isReal: true,
    source: 'B站公开数据 2026年'
  },
  {
    id: 'real017',
    title: 'ChatGPT提示词写作10个黄金公式',
    platform: 'bilibili',
    categoryId: 'aigc',
    author: '波波聊AI',
    authorFollowers: 420000,
    views: 680000,
    likes: 68000,
    comments: 4200,
    shares: 8500,
    duration: 2880,
    date: '2026-03-10',
    tags: ['ChatGPT', '提示词', 'Prompt', '黄金公式', '多行业模板', '迭代优化'],
    script: '拆解Prompt结构：场景、角色、约束、示例。提供多行业模板：营销、产品、教育、写作。现场演示如何不断迭代提升输出质量。B站高赞课程，6.8万赞。提示词工程是AI时代的核心技能，这10个公式覆盖了90%的使用场景。',
    videoUrl: '',
    isReal: true,
    source: 'B站公开数据 2026年'
  },
  {
    id: 'real018',
    title: '十分钟揭秘DeepSeek原理，通俗易懂的大语言模型科普',
    platform: 'bilibili',
    categoryId: 'aigc',
    author: '赭川鹤鸣',
    authorFollowers: 280000,
    views: 810000,
    likes: 34700,
    comments: 3200,
    shares: 5600,
    duration: 600,
    date: '2026-02-20',
    tags: ['DeepSeek', '大语言模型', '科普', '通俗易懂', '十分钟', '原理'],
    script: '十分钟揭秘DeepSeek原理，通俗易懂的大语言模型科普。8.1万播放，3474收藏。用最简单的方式解释DeepSeek的技术原理，从模型架构到训练方法，适合所有对AI感兴趣的人。不需要数学基础也能看懂。',
    videoUrl: '',
    isReal: true,
    source: 'B站公开数据 2026年'
  },
  {
    id: 'real019',
    title: '一个视频终结：中美AI产业到底谁强',
    platform: 'bilibili',
    categoryId: 'aigc',
    author: '巫师财经',
    authorFollowers: 980000,
    views: 6070000,
    likes: 120000,
    comments: 8500,
    shares: 15000,
    duration: 1800,
    date: '2026-03-20',
    tags: ['中美AI', '产业分析', '巫师财经', '深度解读', '行业对比'],
    script: '一个视频终结中美AI产业到底谁强。巫师财经出品，60.7万播放。从中美AI企业数量、融资金额、技术差距、人才储备、政策环境等多个维度进行深度对比分析。适合想了解AI行业宏观格局的人。',
    videoUrl: '',
    isReal: true,
    source: 'B站公开数据 2026年'
  },
  {
    id: 'real020',
    title: 'Claude Code详细攻略，一期视频精通（30个进阶技巧）',
    platform: 'bilibili',
    categoryId: 'aigc',
    author: '技术爬爬虾',
    authorFollowers: 180000,
    views: 1440000,
    likes: 6972,
    comments: 890,
    shares: 2200,
    duration: 3600,
    date: '2026-04-05',
    tags: ['Claude Code', 'AI编程', '进阶技巧', '30个', '实操', '编程效率'],
    script: 'Claude Code详细攻略，一期视频精通，30个进阶技巧。14.4万播放，6972收藏。技术爬爬虾出品，适合有一定编程基础想用AI提升开发效率的开发者。从基础配置到高级工作流，30个实用技巧覆盖了日常开发的主要场景。',
    videoUrl: '',
    isReal: true,
    source: 'B站公开数据 2026年'
  },
  {
    id: 'real021',
    title: '清华NLP刘知远团队大模型公开课：从入门到实战',
    platform: 'bilibili',
    categoryId: 'aigc',
    author: 'OpenBMB · 清华大学NLP实验室',
    authorFollowers: 350000,
    views: 6560000,
    likes: 50000,
    comments: 6200,
    shares: 9800,
    duration: 5400,
    date: '2026-01-25',
    tags: ['清华NLP', '刘知远', '大模型', '公开课', '从入门到实战', '权威课程'],
    script: '清华NLP刘知远团队大模型公开课全网首发，带你从入门到实战。OpenBMB出品，清华大学NLP实验室。65.6万播放，5.0万收藏。国内最权威的大模型课程之一，从理论基础到实际部署，系统全面。',
    videoUrl: '',
    isReal: true,
    source: 'B站公开数据 2026年'
  },
  {
    id: 'real022',
    title: 'AI短视频创作完整教学：吃透AI爆款底层原理',
    platform: 'douyin',
    categoryId: 'aigc',
    author: 'AI短视频教学',
    authorFollowers: 220000,
    views: 3200000,
    likes: 45000,
    comments: 3200,
    shares: 8900,
    duration: 600,
    date: '2026-06-01',
    tags: ['AI短视频', '爆款原理', '算法解析', '即梦AI', '实操演示', '全链路'],
    script: '这门AI短视频创作完整教学课程，结合了千万粉丝博主的实战案例，带你深度拆解多平台推荐算法的底层逻辑。从账号权重提升、养号技巧，到区分真假爆款、冷启动起量方法，课程内容系统全面。课程完整讲解了AI赋能短视频的底层逻辑，并配套即梦AI的实操演示，帮助你打通算法认知与AI创作落地的全链路。',
    videoUrl: '',
    isReal: true,
    source: '猎人社 2026年6月'
  },
  {
    id: 'real023',
    title: '从AI视频到直播变现：DeepSeek/即梦AI工具实战教学',
    platform: 'douyin',
    categoryId: 'aigc',
    author: 'AI实战教学',
    authorFollowers: 180000,
    views: 2800000,
    likes: 38000,
    comments: 2800,
    shares: 6500,
    duration: 480,
    date: '2026-05-20',
    tags: ['DeepSeek', '即梦', 'AI变现', '直播带货', '爆款视频', '抖店', '全流程'],
    script: '从零起步、手把手带你玩转AI自媒体的实战课程。内容覆盖了从AI视频制作、账号运营，到直播带货、抖店开店的完整流程。从认识DeepSeek、即梦等AI工具开始，到制作像"大唐公主"、"小人国"这样的爆款视频，再到剪映剪辑、账号运营技巧，最后连直播话术、抖店投流都教得明明白白。学完就能立刻实操，把学到的技能变成实实在在的收益。',
    videoUrl: '',
    isReal: true,
    source: '猎人社 2026年5月'
  },
  {
    id: 'real024',
    title: '北航90后副教授何静：生成式AI应用实战课',
    platform: 'bilibili',
    categoryId: 'aigc',
    author: '北航何静副教授',
    authorFollowers: 95000,
    views: 520000,
    likes: 18000,
    comments: 2200,
    shares: 4500,
    duration: 3600,
    date: '2026-03-15',
    tags: ['北航', '生成式AI', '零基础', '实操', 'AI绘画', 'AI写作', 'AI智能体'],
    script: '北航90后副教授何静亲授10堂生成式人工智能应用实战课。这不是一门让你"从入门到放弃"的理论课，而是一门"从入门到上瘾"的新生小白AI课。零基础友好：不需要数学公式，不需要编程经验。你会亲手用AI画画、写小说、做PPT、生成短视频脚本、当你的学习助手。包括：秒变艺术家（AI生成头像海报漫画）、效率狂人养成（AI写邮件做周报总结论文）、创意无限公司（AI当编剧导演营销文案）、开启第一个AI智能体。',
    videoUrl: 'https://bilibili.com/video/BV1xH6iBLExu',
    isReal: true,
    source: 'B站公开数据 2026年'
  },
  {
    id: 'real025',
    title: '3步将DeepSeek接入Cursor，免费无限制使用AI编程',
    platform: 'bilibili',
    categoryId: 'aigc',
    author: '狠活AI科技',
    authorFollowers: 120000,
    views: 340000,
    likes: 9240,
    comments: 890,
    shares: 1800,
    duration: 600,
    date: '2026-04-10',
    tags: ['DeepSeek', 'Cursor', 'AI编程', '免费', '无限制', '接入教程'],
    script: '3步将DeepSeek接入Cursor，免费无限制使用AI编程。狠活AI科技出品，3.4万播放。适合想用国产大模型进行AI辅助编程的开发者。步骤简单，跟着做就行。',
    videoUrl: '',
    isReal: true,
    source: 'B站公开数据 2026年'
  },

  /* ======== 其他分类的爆款示例 ======== */
  {
    id: 'demo001',
    title: '我用AI一天做了100张设计图，老板直接加薪了',
    platform: 'douyin',
    categoryId: 'aigc',
    author: 'AI设计老王',
    authorFollowers: 860000,
    views: 2840000,
    likes: 186000,
    comments: 8900,
    shares: 23000,
    duration: 58,
    date: '2026-07-26',
    tags: ['Midjourney', 'AI设计', '效率提升', '职场'],
    script: '说真的，我以前做一张设计图至少3小时。直到我发现了这个AI工作流。第一步，你先让AI帮你生成构图草稿，直接把你的想法告诉它，10秒出5版。第二步，你挑一个方向，让AI细化细节。第三步，你自己微调一下颜色和文字。三步走完，一张图20分钟搞定。我上周用这个方法，一天做了100张图，老板看完直接给我加了薪。你们说，这种效率提升，哪个公司不想要？收藏这条，我下条教你怎么用AI做整套品牌VI。',
    videoUrl: '',
    isReal: false,
    source: '示例数据'
  },
  {
    id: 'demo002',
    title: 'ChatGPT+剪映=全自动视频流水线，小白也能做',
    platform: 'douyin',
    categoryId: 'aigc',
    author: 'AI实战派小林',
    authorFollowers: 520000,
    views: 1950000,
    likes: 142000,
    comments: 7600,
    shares: 18000,
    duration: 72,
    date: '2026-07-25',
    tags: ['ChatGPT', '剪映', '自动化', '视频制作'],
    script: '先别划走！今天教你一套AI全自动做视频的流程。第一步，ChatGPT写文案，你给它一个主题，让它按爆款结构写。第二步，文案丢给剪映的图文成片功能，自动配画面和配音。第三步，你只需要花5分钟调一下节奏和字幕。就这么简单，一条高质量视频30分钟搞定。我上个月用这个方法做了60条视频，涨了8万粉。关键是，不需要你会剪辑，不需要你有团队。评论区扣1，我整理了一份详细的操作文档。',
    videoUrl: '',
    isReal: false,
    source: '示例数据'
  },
  {
    id: 'demo003',
    title: 'AI帮我月入3万的全过程，小白也能复制',
    platform: 'xhs',
    categoryId: 'aigc',
    author: 'AI搞钱日记',
    authorFollowers: 320000,
    views: 1580000,
    likes: 128000,
    comments: 12000,
    shares: 9500,
    duration: 65,
    date: '2026-07-24',
    tags: ['AI变现', '副业', '自由职业'],
    script: '姐妹们！AI真的能搞钱！今天掏心窝分享一下我用AI月入3万的全过程。第一步，用AI帮你写商业文案，接单平台上一单200-500。第二步，用AI做设计图，淘宝上接单一单50-200。第三步，用AI做知识付费内容，打包成课程卖。第四步，用AI做自媒体内容，涨粉变现。四种方式，我第三种和第四种加起来就3万了。重点是，不需要你有任何专业背景，AI帮你干活。收藏这条，我后面会详细拆每一种。',
    videoUrl: '',
    isReal: false,
    source: '示例数据'
  },
  {
    id: 'demo004',
    title: '直播3小时卖了50万，我的选品逻辑全公开',
    platform: 'douyin',
    categoryId: 'ecommerce',
    author: '带货一姐小美',
    authorFollowers: 1200000,
    views: 3600000,
    likes: 285000,
    comments: 15000,
    shares: 42000,
    duration: 85,
    date: '2026-07-26',
    tags: ['直播带货', '选品', '转化率', '复盘'],
    script: '50万怎么卖的？就三个品。第一个品是引流款，9.9的纸巾，不赚钱，就为了把人留住。第二个品是利润款，198的精华液，利润率60%，这是主力。第三个品是爆款，39.9的洗面奶，走量，利润率30%。选品逻辑很简单：引流款留人，利润款赚钱，爆款走量。三个品搭配，3小时50万。很多人直播卖不动，就是因为只有一种品。你要么全是利润款没人来，要么全是引流款不赚钱。记住这个铁三角逻辑，下条我讲怎么排品顺序。',
    videoUrl: '',
    isReal: false,
    source: '示例数据'
  },
  {
    id: 'demo005',
    title: '一个公式写出让10万人转发的文案',
    platform: 'bilibili',
    categoryId: 'knowledge',
    author: '文案老司机',
    authorFollowers: 680000,
    views: 2100000,
    likes: 165000,
    comments: 9200,
    shares: 31000,
    duration: 120,
    date: '2026-07-23',
    tags: ['文案', '爆款公式', '传播学'],
    script: '为什么有的文案10万转发，有的连点赞都没有？今天给你一个公式。痛点+反差+解决方案+情绪锚点=爆款。痛点，就是你开头第一句就要戳中他的痛。反差，就是你给一个意想不到的角度。解决方案，就是你给一个简单可操作的方法。情绪锚点，就是你最后留一个让人想转发的金句。举个例子，痛点：每天加班到11点。反差：但最累的不是身体，是看不到希望。解决方案：三个习惯帮你找回节奏。情绪锚点：打工人的体面，不是加班加出来的。你品品，这个结构是不是万能的？',
    videoUrl: '',
    isReal: false,
    source: '示例数据'
  },
  {
    id: 'demo006',
    title: '一天涨粉2万的秘密，99%的人不知道',
    platform: 'douyin',
    categoryId: 'personal',
    author: '涨粉教练阿杰',
    authorFollowers: 950000,
    views: 4200000,
    likes: 310000,
    comments: 18000,
    shares: 56000,
    duration: 52,
    date: '2026-07-27',
    tags: ['涨粉', '起号', '流量池', '算法'],
    script: '一天2万粉，怎么做到的？就一招：蹭热点+反转人设。热点谁都会蹭，但99%的人蹭错了方向。错误做法：直接模仿热点内容。正确做法：用你自己的视角反着来。举个例子，最近所有人在聊AI替代工作。别人都在说"要失业了"，你偏要说"AI让我3天干了3个月的活"。反着来，流量直接拉满。因为算法推荐的就是有争议的内容。记住，热点本身自带流量，但能爆发的一定是反共识的。你跟大多数人一样，就是流量池底部的炮灰。',
    videoUrl: '',
    isReal: false,
    source: '示例数据'
  },

  /* ======== 2025年最新全网爆款（WebSearch搜索） ======== */
  {
    id: 'auto001',
    title: '《刻板印象宇宙》AI动画短片：全网播放破千万，B站获赞56万',
    platform: 'bilibili',
    categoryId: 'aigc_create',
    author: '梦游牛油果',
    authorFollowers: 160000,
    views: 10000000,
    likes: 560000,
    comments: 28000,
    shares: 45000,
    duration: 420,
    date: '2025-09-10',
    tags: ['AI动画', '瑞克和莫蒂', '二创', '地域梗', '叙事完整', '全网千万'],
    script: '一个建筑设计师，靠自学B站教程，创作出了全网播放量超千万的爆款AI动画短片。以《瑞克和莫蒂》主角穿越到一个极具中国本土特色的"刻板印象宇宙"为主线，将密集的地域梗和辛辣讽刺融合成长达7分钟的完整故事。B站获赞56万，抖音获赞48万，粉丝从不到10万涨到16万。创作者"梦游牛油果"证明：AI让普通人也能做出叙事完整的动画短片。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2025年9月 新榜报道'
  },
  {
    id: 'auto002',
    title: 'AI Rapper科普系列：单条获赞335万转发133万',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: '抽象科普',
    authorFollowers: 1190000,
    views: 50000000,
    likes: 3350000,
    comments: 120000,
    shares: 1330000,
    duration: 60,
    date: '2025-06-16',
    tags: ['AI说唱', '知识科普', 'Rap', '魔性洗脑', '单月涨粉45万', '抖音百万赞'],
    script: '知识以一种奇怪的方式进入了我的大脑。"它努力地拖着货物大步向前迈""货物比他的头还要庞大个上百倍""小蛋白却也从来不会叫苦叫累"——驱动蛋白的知识摇身一变变成了押韵歌词，配上神似《沙威玛传奇》的节奏感旋律，魔性洗脑。单条视频抖音获赞超335万，转发超133万。创作者"抽象科普"从1月开始上传第一条，单月涨粉超45万，粉丝超119万。歌词用DeepSeek写，旋律和画面用AI生成。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2025年6月 新榜报道'
  },
  {
    id: 'auto003',
    title: '唐僧反内耗AI整活：24小时涨100万点赞，博主涨粉20万',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: 'AI整活创作者',
    authorFollowers: 200000,
    views: 30000000,
    likes: 1000000,
    comments: 85000,
    shares: 320000,
    duration: 30,
    date: '2025-11-29',
    tags: ['AI整活', '唐僧', '反内耗', '情绪共鸣', '反差感', '抖音百万赞'],
    script: '视频里的唐僧，穿着锦襕袈裟，手里攥着禅杖，对着镜头吼："师傅我悟了！与其委屈自己当老好人，不如为难妖怪当恶人！"评论区全是"哈哈哈哈""这才是唐僧的真实心声"。24小时涨了100万点赞，博主直接涨粉20万。核心就两个字：情绪共鸣。原本逆来顺受的唐僧突然变成"反内耗大师"，角色反差让人眼前一亮。内容共鸣：拒绝精神内耗，有事直接发飙。制作流程：找语录→AI克隆声音→剪素材→发布，普通人手机就能做。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2025年11月 百家号报道'
  },
  {
    id: 'auto004',
    title: '《九尾狐男妖爱上我》AI短剧：27集播放量超1.8亿',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: '梦婆婆',
    authorFollowers: 450000,
    views: 180000000,
    likes: 6500000,
    comments: 320000,
    shares: 890000,
    duration: 120,
    date: '2025-08-06',
    tags: ['AI短剧', '古偶', '猎奇', '50元制作', '全民制片', '抖音破亿'],
    script: '一部AI短剧在社交平台上引发热议，其"猎奇"的题材和AI生成的奇幻画面，让观众直呼"好癫，但看得停不下来"。27集播放量超1.8亿次。九尾狐、龙女等角色及仙妖大战场景均由AI生成。创作者"梦婆婆"回应："剧情和脑洞都是我自己设计的，还融入了不少当下热点。"单集制作仅需1-2小时，成本可低至"50元制作3集"。从"炫技"到"做内容"，AI短剧正以前所未有的活力重塑短剧市场。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2025年8月 今日头条报道'
  },
  {
    id: 'auto005',
    title: '《猫小猫打工记》动物拟人化AI短剧：播放量超1.4亿',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: 'AI短剧创作者',
    authorFollowers: 380000,
    views: 140000000,
    likes: 5200000,
    comments: 210000,
    shares: 680000,
    duration: 90,
    date: '2025-07-18',
    tags: ['AI短剧', '动物拟人化', '打工记', '情绪共鸣', '下沉市场', '抖音破亿'],
    script: '动物拟人化AI短剧的代表作品，播放量已超1.4亿。这类视频源于对国外热门视频的搬运模仿，迅速在抖音、快手扩散成内容风潮。AI短剧经历快速迭代：从去年《三星堆》《山海奇镜》的炫技奇观，到《猫小猫打工记》的动物拟人化情绪共鸣，再到《九尾狐》的抽象癫剧，AI短剧从展示能力转向情绪表达和类型化，逐步靠拢传统影视行业。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2025年7月 新浪科技报道'
  },
  {
    id: 'auto006',
    title: '《我在古代当首富》AI短剧：上线24小时播放量破1.2亿',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: 'AI短剧团队',
    authorFollowers: 120000,
    views: 120000000,
    likes: 5000000,
    comments: 180000,
    shares: 450000,
    duration: 90,
    date: '2025-08-11',
    tags: ['AI短剧', '穿越', '逆袭', '24小时破亿', '成本不足万元', '3天制作'],
    script: '完全由人工智能生成的AI短剧，上线24小时内播放量突破1.2亿，点赞超500万，迅速登顶热榜。剧本由大模型撰写，角色由AI绘图+语音合成驱动，场景自动渲染，制作成本不足万元，周期仅3天。题材集中于"穿越""逆袭""霸总"等爽文套路，每集1-2分钟，节奏快、冲突强、情绪浓，精准击中下沉市场用户的娱乐需求。有MCN透露，一部AI短剧月广告分成可达数十万元。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2025年8月 今日头条报道'
  },
  {
    id: 'auto007',
    title: '《老妈的心愿》AI情感动画：18分钟细腻刻画东亚母女关系',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: '小文',
    authorFollowers: 85000,
    views: 8000000,
    likes: 450000,
    comments: 32000,
    shares: 68000,
    duration: 1080,
    date: '2025-06-10',
    tags: ['AI动画', '情感短片', '东亚母女', '18分钟', '全民导演', '抖音年度案例'],
    script: '导演小文将一段关于执念、亲情与和解的个人家庭故事，借助AI制作成了一部情感细腻的18分钟动画。影片讲述了女儿从不理解母亲的"执念"，到最后与母亲达成和解，整部短片叙事完整，其中典型的东亚母女情感刻画，让无数观众在抖音评论区直呼"落泪了"。在传统影视投资逻辑中，这类私人化情感表达往往会因"不够商业"被拒之门外，但AI让这种具有独特情感价值的短片产出成为现实。这是抖音2025年"全民导演"趋势的代表案例。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2025年12月 新榜年度报告'
  }
];

/* 爆款直播示例数据 */
const DEMO_STREAMS = [
  {
    id: 's001',
    title: 'AI工具专场：40+款工具一次讲透',
    platform: 'douyin',
    host: 'AI实战派小林',
    categoryId: 'aigc',
    peakViewers: 86000,
    avgViewers: 32000,
    duration: 186,
    sales: 128000,
    orders: 2400,
    gmv: 128000,
    date: '2026-07-26',
    highlights: ['开场5分钟在线破8万', 'AI课程链接转化率12%', '评论区互动率8.5%'],
    tags: ['AI培训', '课程带货', '知识付费']
  },
  {
    id: 's002',
    title: '夏季清仓大促：女装专场',
    platform: 'douyin',
    host: '带货一姐小美',
    categoryId: 'ecommerce',
    peakViewers: 156000,
    avgViewers: 78000,
    duration: 210,
    sales: 86000,
    orders: 18500,
    gmv: 580000,
    date: '2026-07-27',
    highlights: ['开场即爆，峰值15.6万', '利润款转化率9.2%', '返场3次均秒空'],
    tags: ['女装', '清仓', '大促']
  },
  {
    id: 's003',
    title: 'Midjourney零基础到精通直播课',
    platform: 'bilibili',
    host: '设计老王AI课',
    categoryId: 'aigc',
    peakViewers: 42000,
    avgViewers: 18000,
    duration: 165,
    sales: 3200,
    orders: 890,
    gmv: 96000,
    date: '2026-07-25',
    highlights: ['免费试听引流转化21%', '弹幕互动量2.4万', '课程续费率45%'],
    tags: ['Midjourney', '设计培训', 'B站直播']
  },
  {
    id: 's004',
    title: '新手做自媒体第1天：从0到1全流程',
    platform: 'wechat',
    host: '自媒体老张',
    categoryId: 'knowledge',
    peakViewers: 68000,
    avgViewers: 35000,
    duration: 140,
    sales: 5600,
    orders: 1200,
    gmv: 89000,
    date: '2026-07-24',
    highlights: ['视频号推荐流量占比62%', '中年用户群体精准', '付费转化路径极短'],
    tags: ['自媒体', '新手起号', '视频号']
  }
];

/* 爆款元素标签 */
const VIRAL_ELEMENTS = [
  { id: 'pain',      name: '痛点刺激',  icon: '😰', desc: '开头直击用户核心痛点，让人无法划走' },
  { id: 'suspense',  name: '悬念设置',  icon: '🤔', desc: '制造信息缺口，激发好奇心，制造期待' },
  { id: 'data',      name: '数据冲击',  icon: '📊', desc: '用具体数字制造冲击感，增强可信度' },
  { id: 'emotion',   name: '情感共鸣',  icon: '❤️', desc: '唤起用户情感认同，产生转发冲动' },
  { id: 'conflict',  name: '争议对立',  icon: '⚡', desc: '制造反共识观点，引发评论区讨论' },
  { id: 'value',     name: '干货清单',  icon: '📝', desc: '提供明确可执行的价值，触发收藏' },
  { id: 'story',     name: '故事代入',  icon: '📖', desc: '用真实故事拉近距离，增强代入感' },
  { id: 'authority', name: '权威背书',  icon: '🏆', desc: '借助数据/案例/身份建立信任' }
];

/* 平台爆款逻辑 */
const PLATFORM_LOGIC = {
  douyin: {
    name: '抖音爆款逻辑',
    rules: [
      '前3秒必须爆：要么痛点，要么反差，要么悬念',
      '完播率是第一指标：节奏快，信息密度高，不废话',
      '短句为主：每句不超过15字，制造紧凑感',
      '评论区引导：结尾留钩子，引导互动',
      '黄金时间轴：0-3s钩子 → 3-15s铺垫 → 15-30s转折 → 30-50s价值 → 50-60sCTA',
      '口语化：说人话，不说书面语，不用复杂句式'
    ]
  },
  xhs: {
    name: '小红书爆款逻辑',
    rules: [
      '种草感第一：不是卖货，是分享体验',
      'emoji丰富：每段至少1-2个emoji，视觉节奏感',
      '"姐妹们"开头：建立亲近感，降低防备心',
      '具体场景化：描述要具体到画面，不要笼统',
      '标题党但有料：标题吸引人，内容要有干货支撑',
      '标签矩阵：3-5个话题标签，覆盖搜索流量'
    ]
  },
  bilibili: {
    name: 'B站爆款逻辑',
    rules: [
      '信息密度极高：UP主要给干货，不能水',
      '逻辑递进：有起承转合，不是碎片信息堆砌',
      '弹幕梗：适当玩梗，制造弹幕互动点',
      '时长3-10分钟最佳：太短信息不够，太长完播低',
      '观众老爷心态：尊重观众智商，不教条',
      '分区适配：不同分区有不同的内容偏好'
    ]
  },
  kuaishou: {
    name: '快手爆款逻辑',
    rules: [
      '老铁文化：真实、接地气、有人情味',
      '信任经济：人设比内容更重要',
      '直接说事：不绕弯子，开头就说重点',
      '接地气场景：生活化场景，不要精致布景',
      '互动感强：经常喊话老铁，制造参与感'
    ]
  },
  wechat: {
    name: '视频号爆款逻辑',
    rules: [
      '中年受众为主：内容偏价值观、人生感悟',
      '金句感：每条要有1-2句能截图转发的金句',
      '社交推荐制：转发到朋友圈是核心传播路径',
      '信息增量：不能只是观点，要有新信息或新角度',
      '情绪正向：正能量、鸡汤类内容传播力更强'
    ]
  },
  toutiao: {
    name: '今日头条爆款逻辑',
    rules: [
      '标题决定生死：信息量大+悬念+数字',
      '深度内容优先：长文/长视频权重更高',
      '关键词覆盖：标题和正文覆盖搜索热词',
      '时效性：追热点、追时效的内容权重高',
      '互动率：评论和转发是重要推荐指标'
    ]
  }
};

/* 内容来源说明 */
const DATA_SOURCE_INFO = {
  lastUpdate: '2026-07-28',
  totalVideos: 38,
  realVideos: 32,
  demoVideos: 6,
  sources: [
    '新榜数据（new.qq.com）- AI爆款盘点报告',
    'B站公开播放数据',
    '今日头条公开文章',
    'QQ新闻公开报道',
    '58课堂教程信息',
    '猎人社课程信息',
    '新浪科技报道',
    '百家号公开报道',
    'WebSearch全网搜索',
    '平台公开信息整理'
  ],
  limitations: [
    '抖音、快手、小红书等平台无公开内容搜索API',
    '无法自动实时爬取平台数据（反爬机制）',
    '当前数据为人工整理的公开报道信息',
    '如需实时更新，需接入第三方数据服务商API'
  ],
  updateGuide: '系统每日自动搜索全网爆款视频并更新。如需手动添加，请在应用内「内容更新中心」添加，或联系开发者批量导入'
};
