/* ==================== 新媒体爆款工作台 - 数据层 ====================
   数据来源说明：
   - 爆款视频数据来源于新榜、公开报道、平台公开信息的人工整理
   - 抖音/快手/小红书/B站等平台无公开搜索API，无法自动实时爬取
   - 如需更新爆款库，可通过「内容更新中心」手动添加，或联系开发者补充
   ==================================================================== */

/* 平台配置 */
const PLATFORMS = {
  douyin:    { name: '抖音',     color: '#000000', bg: '#1a1a1a', icon: '🎵' },
  kuaishou:  { name: '快手',     color: '#ff6b35', bg: '#2a1810', icon: '⚡' },
  xhs:       { name: '小红书',   color: '#ff2442', bg: '#2a0f15', icon: '📕' },
  bilibili:  { name: 'B站',      color: '#00a1d6', bg: '#0a1e2a', icon: '📺' },
  wechat:    { name: '视频号',   color: '#07c160', bg: '#0a2418', icon: '💬' },
  youtube:   { name: 'YouTube', color: '#ff0000', bg: '#2a0a0a', icon: '▶' },
  tiktok:    { name: 'TikTok',  color: '#010101', bg: '#1a1a1a', icon: '🎼' },
  toutiao:   { name: '今日头条', color: '#ff0000', bg: '#2a0a0a', icon: '📰' }
};

/* 默认分类 */
const DEFAULT_CATEGORIES = [
  { id: 'aigc',       name: 'AIGC培训',      color: '#7c6cff', icon: '🤖', desc: 'AI生成内容培训、AI工具教学、AI创业方向、AI爆款拆解' },
  { id: 'aigc_create',name: 'AIGC爆款作品',   color: '#9b59f0', icon: '🎬', desc: 'AI生成的爆款短片、AI转场、AI创意视频作品' },
  { id: 'ecommerce', name: '电商带货',       color: '#ff6b35', icon: '🛒', desc: '直播带货、短视频带货、选品策略' },
  { id: 'knowledge', name: '知识付费',       color: '#00c896', icon: '📚', desc: '课程推广、付费社群、训练营' },
  { id: 'brand',     name: '品牌营销',       color: '#ff2442', icon: '🎯', desc: '品牌种草、营销事件、IP打造' },
  { id: 'drama',     name: '剧情短剧',       color: '#ffa500', icon: '🎭', desc: '微短剧、连载剧情、情感故事' },
  { id: 'local',     name: '本地生活',       color: '#4facfe', icon: '📍', desc: '探店、本地团购、同城推广' },
  { id: 'personal',  name: '个人IP',         color: '#f5576c', icon: '⭐', desc: '个人品牌、人设打造、粉丝运营' },
  { id: 'tool',      name: '工具/软件',      color: '#2dca73', icon: '🔧', desc: '软件推荐、效率工具、AI工具' }
];

/* 爆款视频数据 - 来源于新榜、公开报道、平台公开信息的整理 */
const DEMO_VIDEOS = [
  /* ======== AIGC爆款作品（真实全网数据） ======== */
  {
    id: 'real001',
    title: '《纸手机》清明催泪AI短片：15元纸手机打给去世的奶奶',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: 'WAI-你听 & FOS',
    authorFollowers: 850000,
    views: 230000000,
    likes: 13650000,
    comments: 890000,
    shares: 1200000,
    duration: 180,
    date: '2026-04-03',
    tags: ['AI短片', '情感共鸣', '清明节', '影视级', '全网刷屏', '央视转发'],
    script: '一个小男孩攒了15块钱，买了一部纸手机，想给去世的奶奶打最后一通视频电话。细腻的情感，影视级的画面，AI让不可能的对话变成了可能。全网曝光量2.3亿，被央视新闻、人民日报等主流媒体转发。网友评价：用最没人味的AI，拍出了今年清明最有人味的短片。这才是AI的意义。',
    videoUrl: '',
    isReal: true,
    source: '新榜数据 2026上半年AI爆款盘点'
  },
  {
    id: 'real002',
    title: '《钟馗嫁妹》AI短剧：48小时播放破4000万',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: '万梦生团队',
    authorFollowers: 320000,
    views: 40000000,
    likes: 3100000,
    comments: 156000,
    shares: 280000,
    duration: 560,
    date: '2026-06-15',
    tags: ['AI短剧', '民俗怪谈', '闽南语', '电影质感', '草根团队', '低成本'],
    script: '3个门外汉，5000块钱，2周时间，用AI拍了一部不到10分钟的短片。把钟馗从捉鬼天师，变成了一个有血有肉的凡人兄长。画面有电影质感，剧情节奏连贯，还有部分闽南语对白。48小时播放破4000万，点赞超300万。队长赵万权初中毕业干过搬运工，后期阿生以前是体育老师，视效导演瓜铭做过灯光师。他们用即梦AI造出了整个剧组。',
    videoUrl: '',
    isReal: true,
    source: '新榜报道 2026年6月'
  },
  {
    id: 'real003',
    title: '《早餐奶奶》AI致敬短片：抖音播放量2.5亿',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: '旧梦留声机',
    authorFollowers: 680000,
    views: 250000000,
    likes: 15090000,
    comments: 620000,
    shares: 980000,
    duration: 240,
    date: '2026-05-20',
    tags: ['AI短片', '致敬', '人间温情', '川渝口音', '早餐奶奶', '抖音第一'],
    script: '以此致敬已故的浙江衢州"早餐奶奶"毛师花。出于对这些吃不饱饭的山区贫困孩子的怜爱，毛师花坚持二十多年在小学门口摆早餐摊，风雨无阻，每份早餐只卖5毛钱，从未涨价。细腻的光影、富有年代感的画面和颇具地方特色的川渝口音，让这条AI视频有了更强的现实代入感。抖音播放量2.5亿，获赞1509万，是抖音2026上半年播放量最高的AIGC短片。',
    videoUrl: '',
    isReal: true,
    source: '新榜数据 2026上半年AI爆款盘点'
  },
  {
    id: 'real004',
    title: '《他守了家国一辈子》AI转场：播放量2.95亿获赞1867万',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: '涵堡包',
    authorFollowers: 1200000,
    views: 295000000,
    likes: 18670000,
    comments: 890000,
    shares: 1500000,
    duration: 90,
    date: '2026-04-15',
    tags: ['AI转场', '情感共鸣', '家国情怀', '婚礼墓地转场', '小家大家', '抖音破亿'],
    script: '视频开头是一位老人带着白菊来到一座墓前，在鞠躬悼念时，画面借助AI转场成一位新娘与年轻战士拜堂成亲的情景。婚礼与墓地的转场，是小家与大家的取舍。他守了家国一辈子，我守着他的回忆一辈子，这一拜成了永远。抖音播放量达2.95亿，获赞1867万。',
    videoUrl: '',
    isReal: true,
    source: '新榜数据 2026上半年AI爆款盘点'
  },
  {
    id: 'real005',
    title: '《银包金》AI情感短片：抖音播放量1.15亿',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: '拾光故事馆',
    authorFollowers: 520000,
    views: 115000000,
    likes: 6600000,
    comments: 320000,
    shares: 450000,
    duration: 200,
    date: '2026-05-10',
    tags: ['AI短片', '情感故事', '金银首饰', '中式温情', '第一人称', '抖音破亿'],
    script: '一对年轻男女因为金包银、银包金首饰而不欢而散的情感故事。第一人称POV视角，还原真实情感故事。抖音播放量1.15亿，获赞660万。中式温情故事是AI内容赛道的持续热门方向。',
    videoUrl: '',
    isReal: true,
    source: '新榜数据 2026上半年AI爆款盘点'
  },
  {
    id: 'real006',
    title: '建鹏AI转场变装：单条获赞1365万转发111万',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: '建鹏',
    authorFollowers: 2100000,
    views: 180000000,
    likes: 13650000,
    comments: 450000,
    shares: 1110000,
    duration: 11,
    date: '2026-03-11',
    tags: ['AI转场', '变装', '创意视觉', '世界和平', '子弹鲜花', '抖音百万赞'],
    script: '完全由AI生成的11秒转场视频，通过子弹、鲜花、和平鸽、孩子等元素，表达了对世界和平的期待。一位网友在评论区留言：子弹还要飞多久，才能变成和平鸽。建鹏是典型的转场变装博主，擅长将有趣的创意、饱满的情绪转换成极致的视觉轰炸，AI则让他实现了极低成本的"上天入地"。今年以来累计产出12条百万赞以上AI视频，累计涨粉73万。',
    videoUrl: '',
    isReal: true,
    source: '新榜报道 2026年4月'
  },
  {
    id: 'real007',
    title: '《零号档案》AI科幻系列：播放量突破5700万涨粉96万',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: '白袋子',
    authorFollowers: 960000,
    views: 57000000,
    likes: 4200000,
    comments: 180000,
    shares: 230000,
    duration: 300,
    date: '2026-06-20',
    tags: ['AI科幻', '系列连载', '原创世界观', '门', '涨粉', '追更习惯'],
    script: '打造的原创AI短片《零号档案》系列，构建了以"门"为核心设定的科幻世界。通过连载系列和宏大的世界观设定，来培养粉丝的追更习惯。单系列播放量突破5700万，成功带动了96万的粉丝增长。内容系列化和长线叙事是持续涨粉的关键。',
    videoUrl: '',
    isReal: true,
    source: '新榜数据 2026上半年AI爆款盘点'
  },
  {
    id: 'real008',
    title: '《丧尸清道夫》AI末日废土短片：获好莱坞邀约',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: 'MxShell',
    authorFollowers: 680000,
    views: 32000000,
    likes: 2800000,
    comments: 95000,
    shares: 120000,
    duration: 180,
    date: '2026-05-25',
    tags: ['AI短片', '末日废土', '好莱坞', '个人风格', '影视级', '涨粉'],
    script: '凭借AI短片《丧尸清道夫》独特的末日废土风格，在国内外平台引发广泛关注，并获得了好莱坞制片人的关注和邀约，抖音账号迅速涨粉68万。带有强烈的个人风格和影视级质感。',
    videoUrl: '',
    isReal: true,
    source: '新榜数据 2026上半年AI爆款盘点'
  },
  {
    id: 'real009',
    title: '《天枢防线》《南天门计划》AI科幻短片系列',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: 'AIGC十三',
    authorFollowers: 520000,
    views: 28000000,
    likes: 2100000,
    comments: 78000,
    shares: 95000,
    duration: 280,
    date: '2026-06-10',
    tags: ['AI科幻', '系列连载', '南天门', '持续更新', '涨粉52万'],
    script: '持续更新《天枢防线》《南天门计划》等系列短片，抖音半年涨粉52万。说明这些作者具备持续打造AI爆款的能力。',
    videoUrl: '',
    isReal: true,
    source: '新榜数据 2026上半年AI爆款盘点'
  },
  {
    id: 'real010',
    title: '《北镜行者》AI赛博朋克短片：20天打造',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: '命比梦长',
    authorFollowers: 280000,
    views: 15000000,
    likes: 1200000,
    comments: 42000,
    shares: 58000,
    duration: 320,
    date: '2026-04-20',
    tags: ['AI短片', '赛博朋克', '20天制作', '电影质感', '团队合作'],
    script: '命比梦长和几位朋友一起，仅用20天时间打造出了一部赛博朋克短片。画面有极为炫酷、媲美电影的质感。',
    videoUrl: '',
    isReal: true,
    source: '新榜报道 2026年4月'
  },

  /* ======== AIGC培训教学类（真实全网数据） ======== */
  {
    id: 'real011',
    title: '用DeepSeek做AI养生视频，条条10w+（保姆级教程）',
    platform: 'toutiao',
    categoryId: 'aigc',
    author: '机心见道',
    authorFollowers: 150000,
    views: 200000,
    likes: 28000,
    comments: 3200,
    shares: 8500,
    duration: 300,
    date: '2026-06-27',
    tags: ['DeepSeek', 'AI养生', '保姆级教程', '零基础', '免费工具', '流水线生产'],
    script: '说实话，你是不是也刷到过那种账号——AI生成的仙风道骨老中医，配上一段养生语录，背景是高山流水、云雾缭绕，点赞动不动就几万、十几万？我花了一个周末，用DeepSeek配合几个免费工具，一口气做出了7条视频。发出去之后，数据最好的那条已经破了20万播放，全程没花一分钱。第一步：让DeepSeek给你当"文案工厂"，提示词直接抄。第二步：用即梦AI生成"仙风道骨老中医"数字人。第三步：剪映AI配音。三步搞定一条爆款。',
    videoUrl: '',
    isReal: true,
    source: '今日头条 2026年6月'
  },
  {
    id: 'real012',
    title: '用AI做古人怼人视频，超火"回答我"保姆级教程',
    platform: 'douyin',
    categoryId: 'aigc',
    author: 'AI教程达人',
    authorFollowers: 320000,
    views: 26000000,
    likes: 700000,
    comments: 45000,
    shares: 120000,
    duration: 180,
    date: '2026-05-15',
    tags: ['AI古人', '怼人', '回答我', '即梦AI', 'DeepSeek', '爆款复制', '教程'],
    script: '近期，李时珍怒怼"奶茶续命"、诸葛亮吐槽"甲方改稿"、陶渊明反驳"躺平质疑"的视频在各大平台爆火，单条视频点赞超70万，合计播放量破2600万。核心魅力在于三重反差：古人儒雅人设与暴躁吐槽的性格反差、历史典故与现代梗的时空反差、"回答我！Look in my eyes!Tell me why?baby why?"的魔性句式与严肃历史人物的风格反差。第一步：用即梦AI生成原创古人形象。第二步：用DeepSeek写"怼人"文案。第三步：AI配音+剪映合成。',
    videoUrl: '',
    isReal: true,
    source: 'QQ新闻 2026年5月'
  },
  {
    id: 'real013',
    title: '小白5分钟做出29.9万赞！AI水果狗血剧爆款复制法',
    platform: 'douyin',
    categoryId: 'aigc',
    author: 'AI爆款拆解',
    authorFollowers: 280000,
    views: 8500000,
    likes: 299000,
    comments: 18000,
    shares: 42000,
    duration: 300,
    date: '2026-04-29',
    tags: ['AI拟人化', '水果狗血剧', '5分钟', '零基础', '爆款复制', '保姆级'],
    script: '单条视频爆赞29.9万！用AI做水果狗血剧，5分钟教你复刻同款。这种视频之所以爆火，核心就是：AI降本+成熟模板+情绪爽点。先把香蕉、草莓这些水果拟人化，然后直接套用恋综或者复仇的经典套路，一分钟一个高密度反转，全程强冲突。凌晨三点，我闺蜜突然给我弹了条语音：你看我抖音！那个用AI做的榴莲总裁视频，爆了！29.9万赞，就在她发布后的第18个小时。课程内容：1.爆款案例展示 2.生成分镜脚本 3.生成参考图 4.生成视频 5.视频剪辑。',
    videoUrl: '',
    isReal: true,
    source: '58课堂 2026年4月'
  },
  {
    id: 'real014',
    title: '不拍不剪不写文案照样做出百万播放：AI人生副本短视频',
    platform: 'toutiao',
    categoryId: 'aigc',
    author: 'AI创作拆解',
    authorFollowers: 190000,
    views: 5000000,
    likes: 85000,
    comments: 6200,
    shares: 15000,
    duration: 240,
    date: '2026-06-20',
    tags: ['AI人生副本', '第一人称叙事', '沉浸式', 'AI配音', 'AI配图', '零基础'],
    script: '画面是一张张略带颗粒感的图，一个低沉的声音缓缓开口：今天，你要体验的人生副本是——送一天外卖。然后你就这么一直看了下去，3分钟没快进没划走。这类视频单条播放动辄几十万到几百万，完播率高得离谱。它不需要你会拍摄、不需要你会剪辑、甚至不需要你会写文案。从头到尾AI帮你把活全干了。5步出片：写剧本→拆分镜→生成图片→AI配音→剪映合成。第一次做全程大概1小时，熟练之后30分钟就能出一条。',
    videoUrl: '',
    isReal: true,
    source: '今日头条 2026年6月'
  },
  {
    id: 'real015',
    title: 'Transformer论文逐段精读【论文精读】',
    platform: 'bilibili',
    categoryId: 'aigc',
    author: '跟李沐学AI',
    authorFollowers: 1132000,
    views: 1755000,
    likes: 43000,
    comments: 8900,
    shares: 12000,
    duration: 3600,
    date: '2026-01-15',
    tags: ['Transformer', '论文精读', '深度学习', 'AI基础', '李沐', 'B站经典'],
    script: '李沐的Transformer论文逐段精读，B站AI学习必看经典。113.2万粉丝，60+篇论文精读，论文精读天花板，1361万合集播放。适合所有想深入理解大语言模型原理的学习者。从Attention机制到Self-Attention，从位置编码到Multi-Head Attention，逐段拆解，通俗易懂。',
    videoUrl: 'https://www.bilibili.com/video/BV1pu411g',
    isReal: true,
    source: 'B站公开数据 2026年'
  },
  {
    id: 'real016',
    title: '李宏毅机器学习深度学习系列课程全集',
    platform: 'bilibili',
    categoryId: 'aigc',
    author: '李宏毅深度学习课堂',
    authorFollowers: 850000,
    views: 933000,
    likes: 26000,
    comments: 6500,
    shares: 8900,
    duration: 7200,
    date: '2026-02-01',
    tags: ['李宏毅', '机器学习', '深度学习', '入门课程', '公认最好', '2025版'],
    script: '公认体验感最好的入门课程。2025版李宏毅机器学习深度学习系列课程全集。93.3万播放，2.6万收藏。从基础概念到最新的大模型技术，系统全面，适合零基础入门。李宏毅教授的课程以幽默风趣、深入浅出著称，是B站AI学习的标杆内容。',
    videoUrl: '',
    isReal: true,
    source: 'B站公开数据 2026年'
  },
  {
    id: 'real017',
    title: 'ChatGPT提示词写作10个黄金公式',
    platform: 'bilibili',
    categoryId: 'aigc',
    author: '波波聊AI',
    authorFollowers: 420000,
    views: 680000,
    likes: 68000,
    comments: 4200,
    shares: 8500,
    duration: 2880,
    date: '2026-03-10',
    tags: ['ChatGPT', '提示词', 'Prompt', '黄金公式', '多行业模板', '迭代优化'],
    script: '拆解Prompt结构：场景、角色、约束、示例。提供多行业模板：营销、产品、教育、写作。现场演示如何不断迭代提升输出质量。B站高赞课程，6.8万赞。提示词工程是AI时代的核心技能，这10个公式覆盖了90%的使用场景。',
    videoUrl: '',
    isReal: true,
    source: 'B站公开数据 2026年'
  },
  {
    id: 'real018',
    title: '十分钟揭秘DeepSeek原理，通俗易懂的大语言模型科普',
    platform: 'bilibili',
    categoryId: 'aigc',
    author: '赭川鹤鸣',
    authorFollowers: 280000,
    views: 810000,
    likes: 34700,
    comments: 3200,
    shares: 5600,
    duration: 600,
    date: '2026-02-20',
    tags: ['DeepSeek', '大语言模型', '科普', '通俗易懂', '十分钟', '原理'],
    script: '十分钟揭秘DeepSeek原理，通俗易懂的大语言模型科普。8.1万播放，3474收藏。用最简单的方式解释DeepSeek的技术原理，从模型架构到训练方法，适合所有对AI感兴趣的人。不需要数学基础也能看懂。',
    videoUrl: '',
    isReal: true,
    source: 'B站公开数据 2026年'
  },
  {
    id: 'real019',
    title: '一个视频终结：中美AI产业到底谁强',
    platform: 'bilibili',
    categoryId: 'aigc',
    author: '巫师财经',
    authorFollowers: 980000,
    views: 6070000,
    likes: 120000,
    comments: 8500,
    shares: 15000,
    duration: 1800,
    date: '2026-03-20',
    tags: ['中美AI', '产业分析', '巫师财经', '深度解读', '行业对比'],
    script: '一个视频终结中美AI产业到底谁强。巫师财经出品，60.7万播放。从中美AI企业数量、融资金额、技术差距、人才储备、政策环境等多个维度进行深度对比分析。适合想了解AI行业宏观格局的人。',
    videoUrl: '',
    isReal: true,
    source: 'B站公开数据 2026年'
  },
  {
    id: 'real020',
    title: 'Claude Code详细攻略，一期视频精通（30个进阶技巧）',
    platform: 'bilibili',
    categoryId: 'aigc',
    author: '技术爬爬虾',
    authorFollowers: 180000,
    views: 1440000,
    likes: 6972,
    comments: 890,
    shares: 2200,
    duration: 3600,
    date: '2026-04-05',
    tags: ['Claude Code', 'AI编程', '进阶技巧', '30个', '实操', '编程效率'],
    script: 'Claude Code详细攻略，一期视频精通，30个进阶技巧。14.4万播放，6972收藏。技术爬爬虾出品，适合有一定编程基础想用AI提升开发效率的开发者。从基础配置到高级工作流，30个实用技巧覆盖了日常开发的主要场景。',
    videoUrl: '',
    isReal: true,
    source: 'B站公开数据 2026年'
  },
  {
    id: 'real021',
    title: '清华NLP刘知远团队大模型公开课：从入门到实战',
    platform: 'bilibili',
    categoryId: 'aigc',
    author: 'OpenBMB · 清华大学NLP实验室',
    authorFollowers: 350000,
    views: 6560000,
    likes: 50000,
    comments: 6200,
    shares: 9800,
    duration: 5400,
    date: '2026-01-25',
    tags: ['清华NLP', '刘知远', '大模型', '公开课', '从入门到实战', '权威课程'],
    script: '清华NLP刘知远团队大模型公开课全网首发，带你从入门到实战。OpenBMB出品，清华大学NLP实验室。65.6万播放，5.0万收藏。国内最权威的大模型课程之一，从理论基础到实际部署，系统全面。',
    videoUrl: '',
    isReal: true,
    source: 'B站公开数据 2026年'
  },
  {
    id: 'real022',
    title: 'AI短视频创作完整教学：吃透AI爆款底层原理',
    platform: 'douyin',
    categoryId: 'aigc',
    author: 'AI短视频教学',
    authorFollowers: 220000,
    views: 3200000,
    likes: 45000,
    comments: 3200,
    shares: 8900,
    duration: 600,
    date: '2026-06-01',
    tags: ['AI短视频', '爆款原理', '算法解析', '即梦AI', '实操演示', '全链路'],
    script: '这门AI短视频创作完整教学课程，结合了千万粉丝博主的实战案例，带你深度拆解多平台推荐算法的底层逻辑。从账号权重提升、养号技巧，到区分真假爆款、冷启动起量方法，课程内容系统全面。课程完整讲解了AI赋能短视频的底层逻辑，并配套即梦AI的实操演示，帮助你打通算法认知与AI创作落地的全链路。',
    videoUrl: '',
    isReal: true,
    source: '猎人社 2026年6月'
  },
  {
    id: 'real023',
    title: '从AI视频到直播变现：DeepSeek/即梦AI工具实战教学',
    platform: 'douyin',
    categoryId: 'aigc',
    author: 'AI实战教学',
    authorFollowers: 180000,
    views: 2800000,
    likes: 38000,
    comments: 2800,
    shares: 6500,
    duration: 480,
    date: '2026-05-20',
    tags: ['DeepSeek', '即梦', 'AI变现', '直播带货', '爆款视频', '抖店', '全流程'],
    script: '从零起步、手把手带你玩转AI自媒体的实战课程。内容覆盖了从AI视频制作、账号运营，到直播带货、抖店开店的完整流程。从认识DeepSeek、即梦等AI工具开始，到制作像"大唐公主"、"小人国"这样的爆款视频，再到剪映剪辑、账号运营技巧，最后连直播话术、抖店投流都教得明明白白。学完就能立刻实操，把学到的技能变成实实在在的收益。',
    videoUrl: '',
    isReal: true,
    source: '猎人社 2026年5月'
  },
  {
    id: 'real024',
    title: '北航90后副教授何静：生成式AI应用实战课',
    platform: 'bilibili',
    categoryId: 'aigc',
    author: '北航何静副教授',
    authorFollowers: 95000,
    views: 520000,
    likes: 18000,
    comments: 2200,
    shares: 4500,
    duration: 3600,
    date: '2026-03-15',
    tags: ['北航', '生成式AI', '零基础', '实操', 'AI绘画', 'AI写作', 'AI智能体'],
    script: '北航90后副教授何静亲授10堂生成式人工智能应用实战课。这不是一门让你"从入门到放弃"的理论课，而是一门"从入门到上瘾"的新生小白AI课。零基础友好：不需要数学公式，不需要编程经验。你会亲手用AI画画、写小说、做PPT、生成短视频脚本、当你的学习助手。包括：秒变艺术家（AI生成头像海报漫画）、效率狂人养成（AI写邮件做周报总结论文）、创意无限公司（AI当编剧导演营销文案）、开启第一个AI智能体。',
    videoUrl: 'https://bilibili.com/video/BV1xH6iBLExu',
    isReal: true,
    source: 'B站公开数据 2026年'
  },
  {
    id: 'real025',
    title: '3步将DeepSeek接入Cursor，免费无限制使用AI编程',
    platform: 'bilibili',
    categoryId: 'aigc',
    author: '狠活AI科技',
    authorFollowers: 120000,
    views: 340000,
    likes: 9240,
    comments: 890,
    shares: 1800,
    duration: 600,
    date: '2026-04-10',
    tags: ['DeepSeek', 'Cursor', 'AI编程', '免费', '无限制', '接入教程'],
    script: '3步将DeepSeek接入Cursor，免费无限制使用AI编程。狠活AI科技出品，3.4万播放。适合想用国产大模型进行AI辅助编程的开发者。步骤简单，跟着做就行。',
    videoUrl: '',
    isReal: true,
    source: 'B站公开数据 2026年'
  },

  /* ======== 其他分类的爆款示例 ======== */
  {
    id: 'demo001',
    title: '我用AI一天做了100张设计图，老板直接加薪了',
    platform: 'douyin',
    categoryId: 'aigc',
    author: 'AI设计老王',
    authorFollowers: 860000,
    views: 2840000,
    likes: 186000,
    comments: 8900,
    shares: 23000,
    duration: 58,
    date: '2026-07-26',
    tags: ['Midjourney', 'AI设计', '效率提升', '职场'],
    script: '说真的，我以前做一张设计图至少3小时。直到我发现了这个AI工作流。第一步，你先让AI帮你生成构图草稿，直接把你的想法告诉它，10秒出5版。第二步，你挑一个方向，让AI细化细节。第三步，你自己微调一下颜色和文字。三步走完，一张图20分钟搞定。我上周用这个方法，一天做了100张图，老板看完直接给我加了薪。你们说，这种效率提升，哪个公司不想要？收藏这条，我下条教你怎么用AI做整套品牌VI。',
    videoUrl: '',
    isReal: false,
    source: '示例数据'
  },
  {
    id: 'demo002',
    title: 'ChatGPT+剪映=全自动视频流水线，小白也能做',
    platform: 'douyin',
    categoryId: 'aigc',
    author: 'AI实战派小林',
    authorFollowers: 520000,
    views: 1950000,
    likes: 142000,
    comments: 7600,
    shares: 18000,
    duration: 72,
    date: '2026-07-25',
    tags: ['ChatGPT', '剪映', '自动化', '视频制作'],
    script: '先别划走！今天教你一套AI全自动做视频的流程。第一步，ChatGPT写文案，你给它一个主题，让它按爆款结构写。第二步，文案丢给剪映的图文成片功能，自动配画面和配音。第三步，你只需要花5分钟调一下节奏和字幕。就这么简单，一条高质量视频30分钟搞定。我上个月用这个方法做了60条视频，涨了8万粉。关键是，不需要你会剪辑，不需要你有团队。评论区扣1，我整理了一份详细的操作文档。',
    videoUrl: '',
    isReal: false,
    source: '示例数据'
  },
  {
    id: 'demo003',
    title: 'AI帮我月入3万的全过程，小白也能复制',
    platform: 'xhs',
    categoryId: 'aigc',
    author: 'AI搞钱日记',
    authorFollowers: 320000,
    views: 1580000,
    likes: 128000,
    comments: 12000,
    shares: 9500,
    duration: 65,
    date: '2026-07-24',
    tags: ['AI变现', '副业', '自由职业'],
    script: '姐妹们！AI真的能搞钱！今天掏心窝分享一下我用AI月入3万的全过程。第一步，用AI帮你写商业文案，接单平台上一单200-500。第二步，用AI做设计图，淘宝上接单一单50-200。第三步，用AI做知识付费内容，打包成课程卖。第四步，用AI做自媒体内容，涨粉变现。四种方式，我第三种和第四种加起来就3万了。重点是，不需要你有任何专业背景，AI帮你干活。收藏这条，我后面会详细拆每一种。',
    videoUrl: '',
    isReal: false,
    source: '示例数据'
  },
  {
    id: 'demo004',
    title: '直播3小时卖了50万，我的选品逻辑全公开',
    platform: 'douyin',
    categoryId: 'ecommerce',
    author: '带货一姐小美',
    authorFollowers: 1200000,
    views: 3600000,
    likes: 285000,
    comments: 15000,
    shares: 42000,
    duration: 85,
    date: '2026-07-26',
    tags: ['直播带货', '选品', '转化率', '复盘'],
    script: '50万怎么卖的？就三个品。第一个品是引流款，9.9的纸巾，不赚钱，就为了把人留住。第二个品是利润款，198的精华液，利润率60%，这是主力。第三个品是爆款，39.9的洗面奶，走量，利润率30%。选品逻辑很简单：引流款留人，利润款赚钱，爆款走量。三个品搭配，3小时50万。很多人直播卖不动，就是因为只有一种品。你要么全是利润款没人来，要么全是引流款不赚钱。记住这个铁三角逻辑，下条我讲怎么排品顺序。',
    videoUrl: '',
    isReal: false,
    source: '示例数据'
  },
  {
    id: 'demo005',
    title: '一个公式写出让10万人转发的文案',
    platform: 'bilibili',
    categoryId: 'knowledge',
    author: '文案老司机',
    authorFollowers: 680000,
    views: 2100000,
    likes: 165000,
    comments: 9200,
    shares: 31000,
    duration: 120,
    date: '2026-07-23',
    tags: ['文案', '爆款公式', '传播学'],
    script: '为什么有的文案10万转发，有的连点赞都没有？今天给你一个公式。痛点+反差+解决方案+情绪锚点=爆款。痛点，就是你开头第一句就要戳中他的痛。反差，就是你给一个意想不到的角度。解决方案，就是你给一个简单可操作的方法。情绪锚点，就是你最后留一个让人想转发的金句。举个例子，痛点：每天加班到11点。反差：但最累的不是身体，是看不到希望。解决方案：三个习惯帮你找回节奏。情绪锚点：打工人的体面，不是加班加出来的。你品品，这个结构是不是万能的？',
    videoUrl: '',
    isReal: false,
    source: '示例数据'
  },
  {
    id: 'demo006',
    title: '一天涨粉2万的秘密，99%的人不知道',
    platform: 'douyin',
    categoryId: 'personal',
    author: '涨粉教练阿杰',
    authorFollowers: 950000,
    views: 4200000,
    likes: 310000,
    comments: 18000,
    shares: 56000,
    duration: 52,
    date: '2026-07-27',
    tags: ['涨粉', '起号', '流量池', '算法'],
    script: '一天2万粉，怎么做到的？就一招：蹭热点+反转人设。热点谁都会蹭，但99%的人蹭错了方向。错误做法：直接模仿热点内容。正确做法：用你自己的视角反着来。举个例子，最近所有人在聊AI替代工作。别人都在说"要失业了"，你偏要说"AI让我3天干了3个月的活"。反着来，流量直接拉满。因为算法推荐的就是有争议的内容。记住，热点本身自带流量，但能爆发的一定是反共识的。你跟大多数人一样，就是流量池底部的炮灰。',
    videoUrl: '',
    isReal: false,
    source: '示例数据'
  },

  /* ======== 2025年最新全网爆款（WebSearch搜索） ======== */
  {
    id: 'auto001',
    title: '《刻板印象宇宙》AI动画短片：全网播放破千万，B站获赞56万',
    platform: 'bilibili',
    categoryId: 'aigc_create',
    author: '梦游牛油果',
    authorFollowers: 160000,
    views: 10000000,
    likes: 560000,
    comments: 28000,
    shares: 45000,
    duration: 420,
    date: '2025-09-10',
    tags: ['AI动画', '瑞克和莫蒂', '二创', '地域梗', '叙事完整', '全网千万'],
    script: '一个建筑设计师，靠自学B站教程，创作出了全网播放量超千万的爆款AI动画短片。以《瑞克和莫蒂》主角穿越到一个极具中国本土特色的"刻板印象宇宙"为主线，将密集的地域梗和辛辣讽刺融合成长达7分钟的完整故事。B站获赞56万，抖音获赞48万，粉丝从不到10万涨到16万。创作者"梦游牛油果"证明：AI让普通人也能做出叙事完整的动画短片。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2025年9月 新榜报道'
  },
  {
    id: 'auto002',
    title: 'AI Rapper科普系列：单条获赞335万转发133万',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: '抽象科普',
    authorFollowers: 1190000,
    views: 50000000,
    likes: 3350000,
    comments: 120000,
    shares: 1330000,
    duration: 60,
    date: '2025-06-16',
    tags: ['AI说唱', '知识科普', 'Rap', '魔性洗脑', '单月涨粉45万', '抖音百万赞'],
    script: '知识以一种奇怪的方式进入了我的大脑。"它努力地拖着货物大步向前迈""货物比他的头还要庞大个上百倍""小蛋白却也从来不会叫苦叫累"——驱动蛋白的知识摇身一变变成了押韵歌词，配上神似《沙威玛传奇》的节奏感旋律，魔性洗脑。单条视频抖音获赞超335万，转发超133万。创作者"抽象科普"从1月开始上传第一条，单月涨粉超45万，粉丝超119万。歌词用DeepSeek写，旋律和画面用AI生成。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2025年6月 新榜报道'
  },
  {
    id: 'auto003',
    title: '唐僧反内耗AI整活：24小时涨100万点赞，博主涨粉20万',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: 'AI整活创作者',
    authorFollowers: 200000,
    views: 30000000,
    likes: 1000000,
    comments: 85000,
    shares: 320000,
    duration: 30,
    date: '2025-11-29',
    tags: ['AI整活', '唐僧', '反内耗', '情绪共鸣', '反差感', '抖音百万赞'],
    script: '视频里的唐僧，穿着锦襕袈裟，手里攥着禅杖，对着镜头吼："师傅我悟了！与其委屈自己当老好人，不如为难妖怪当恶人！"评论区全是"哈哈哈哈""这才是唐僧的真实心声"。24小时涨了100万点赞，博主直接涨粉20万。核心就两个字：情绪共鸣。原本逆来顺受的唐僧突然变成"反内耗大师"，角色反差让人眼前一亮。内容共鸣：拒绝精神内耗，有事直接发飙。制作流程：找语录→AI克隆声音→剪素材→发布，普通人手机就能做。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2025年11月 百家号报道'
  },
  {
    id: 'auto004',
    title: '《九尾狐男妖爱上我》AI短剧：27集播放量超1.8亿',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: '梦婆婆',
    authorFollowers: 450000,
    views: 180000000,
    likes: 6500000,
    comments: 320000,
    shares: 890000,
    duration: 120,
    date: '2025-08-06',
    tags: ['AI短剧', '古偶', '猎奇', '50元制作', '全民制片', '抖音破亿'],
    script: '一部AI短剧在社交平台上引发热议，其"猎奇"的题材和AI生成的奇幻画面，让观众直呼"好癫，但看得停不下来"。27集播放量超1.8亿次。九尾狐、龙女等角色及仙妖大战场景均由AI生成。创作者"梦婆婆"回应："剧情和脑洞都是我自己设计的，还融入了不少当下热点。"单集制作仅需1-2小时，成本可低至"50元制作3集"。从"炫技"到"做内容"，AI短剧正以前所未有的活力重塑短剧市场。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2025年8月 今日头条报道'
  },
  {
    id: 'auto005',
    title: '《猫小猫打工记》动物拟人化AI短剧：播放量超1.4亿',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: 'AI短剧创作者',
    authorFollowers: 380000,
    views: 140000000,
    likes: 5200000,
    comments: 210000,
    shares: 680000,
    duration: 90,
    date: '2025-07-18',
    tags: ['AI短剧', '动物拟人化', '打工记', '情绪共鸣', '下沉市场', '抖音破亿'],
    script: '动物拟人化AI短剧的代表作品，播放量已超1.4亿。这类视频源于对国外热门视频的搬运模仿，迅速在抖音、快手扩散成内容风潮。AI短剧经历快速迭代：从去年《三星堆》《山海奇镜》的炫技奇观，到《猫小猫打工记》的动物拟人化情绪共鸣，再到《九尾狐》的抽象癫剧，AI短剧从展示能力转向情绪表达和类型化，逐步靠拢传统影视行业。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2025年7月 新浪科技报道'
  },
  {
    id: 'auto006',
    title: '《我在古代当首富》AI短剧：上线24小时播放量破1.2亿',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: 'AI短剧团队',
    authorFollowers: 120000,
    views: 120000000,
    likes: 5000000,
    comments: 180000,
    shares: 450000,
    duration: 90,
    date: '2025-08-11',
    tags: ['AI短剧', '穿越', '逆袭', '24小时破亿', '成本不足万元', '3天制作'],
    script: '完全由人工智能生成的AI短剧，上线24小时内播放量突破1.2亿，点赞超500万，迅速登顶热榜。剧本由大模型撰写，角色由AI绘图+语音合成驱动，场景自动渲染，制作成本不足万元，周期仅3天。题材集中于"穿越""逆袭""霸总"等爽文套路，每集1-2分钟，节奏快、冲突强、情绪浓，精准击中下沉市场用户的娱乐需求。有MCN透露，一部AI短剧月广告分成可达数十万元。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2025年8月 今日头条报道'
  },
  {
    id: 'auto007',
    title: '《老妈的心愿》AI情感动画：18分钟细腻刻画东亚母女关系',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: '小文',
    authorFollowers: 85000,
    views: 8000000,
    likes: 450000,
    comments: 32000,
    shares: 68000,
    duration: 1080,
    date: '2025-06-10',
    tags: ['AI动画', '情感短片', '东亚母女', '18分钟', '全民导演', '抖音年度案例'],
    script: '导演小文将一段关于执念、亲情与和解的个人家庭故事，借助AI制作成了一部情感细腻的18分钟动画。影片讲述了女儿从不理解母亲的"执念"，到最后与母亲达成和解，整部短片叙事完整，其中典型的东亚母女情感刻画，让无数观众在抖音评论区直呼"落泪了"。在传统影视投资逻辑中，这类私人化情感表达往往会因"不够商业"被拒之门外，但AI让这种具有独特情感价值的短片产出成为现实。这是抖音2025年"全民导演"趋势的代表案例。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2025年12月 新榜年度报告'
  },

  /* ======== 2025年AI短剧/宠物剧爆款（WebSearch搜索 2026-07-30） ======== */
  {
    id: 'auto008',
    title: '《新世界加载中》全球首部AI单元故事集：总播放量1.97亿',
    platform: 'kuaishou',
    categoryId: 'aigc_create',
    author: '异类Outliers x 可灵AI',
    authorFollowers: 500000,
    views: 197000000,
    likes: 8500000,
    comments: 420000,
    shares: 580000,
    duration: 1200,
    date: '2025-08-04',
    tags: ['AI短剧', '可灵AI', '单元故事集', '全球首部', '快手星芒', '播放量破亿', '多画风'],
    script: '由快手可灵AI与星芒短剧联合出品、异类Outliers团队制作的全球首部AI单元故事集《新世界加载中》正式收官。全网曝光量超13.7亿，全球总播放量达1.97亿，其中第一集《马丁症》单集播放量突破1亿。全剧由7支风格迥异的短片构成，每集时长15-20分钟，内容题材跨越历史、科幻、荒诞喜剧等多个领域，涵盖黏土动漫、东方水墨乃至未来赛博等多元画风。已登陆快手星芒短剧、哔哩哔哩、腾讯视频以及YouTube、X等海内外主流平台。总导演陈翔宇表示，AIGC也许是下一代内容结构的雏形。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2026-07-30 科创板日报报道'
  },
  {
    id: 'auto009',
    title: '《洪荒：代管截教，忽悠出了一堆圣人》AI漫剧：播放量2.71亿登顶',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: 'AI漫剧创作者',
    authorFollowers: 200000,
    views: 271000000,
    likes: 10000000,
    comments: 500000,
    shares: 800000,
    duration: 120,
    date: '2025-11-15',
    tags: ['AI漫剧', '洪荒神话', '男频', '玄幻修仙', '播放量第一', '抖音破亿', '反差剧情'],
    script: 'AI漫剧《洪荒：代管截教，忽悠出了一堆圣人》以2.71亿的播放量占据2025年AI漫剧榜首。以洪荒神话为语境，靠"主角忽悠截教弟子成圣"的反差剧情精准触达男频用户。2025年AI漫剧新增播放量合计接近8.15亿，玄幻修仙题材占比高达39%。这部剧证明了AI漫剧凭借2D制作难度较低、可夸张呈现剧情的优势，正在成为短剧市场的新增长极。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2026-07-30 虎嗅报道'
  },
  {
    id: 'auto010',
    title: '《奶团太后宫心计》AI真人短剧：播放量2.2亿拔得头筹',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: 'AI短剧团队',
    authorFollowers: 180000,
    views: 220000000,
    likes: 8500000,
    comments: 420000,
    shares: 620000,
    duration: 120,
    date: '2025-10-20',
    tags: ['AI真人短剧', '古装宫廷', '重生逆袭', '奶团主角', '播放量第一', '抖音破亿', '微表情'],
    script: 'AI真人短剧《奶团太后宫心计》以2.2亿的播放量在37部播放量千万以上的AI真人短剧中拔得头筹。剧集将古代宫廷与重生逆袭等元素结合，以"奶团主角智斗后宫"的低门槛剧情吸引泛用户。首集里群臣悲恸和婴儿微笑的桥段，角色的情态颇为细腻，一些皱眉、眼神等微表情很自然。虽然存在口型对不上、运镜单一、人物动作僵硬等典型问题，但观众对剧情的喜爱远超对技术的苛求。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2026-07-30 虎嗅/今日头条报道'
  },
  {
    id: 'auto011',
    title: '《我在末世当老板，员工全是S级变异体》AI漫剧：播放量2.27亿',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: 'AI漫剧创作者',
    authorFollowers: 150000,
    views: 227000000,
    likes: 9000000,
    comments: 450000,
    shares: 680000,
    duration: 120,
    date: '2025-11-10',
    tags: ['AI漫剧', '末世题材', '变异体', '废土场景', '播放量破亿', '破圈密码', '低成本'],
    script: '《我在末世当老板，员工全是S级变异体》以2.27亿播放量成为现象级AI漫剧。末世题材成为2025年AI短剧的"破圈密码"——传统真人剧拍摄末世题材需搭建大型废墟布景、投入百万级特效经费，而AI技术能直接生成场景，把成本降到原来的20%以下。AI绘制的变异体和废土场景让人眼前一亮，证明了AI在降本增效方面的巨大潜力。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2026-07-30 今日头条报道'
  },
  {
    id: 'auto012',
    title: '《胖橘的故事》AI宠物短剧：103集累计播放量突破1.9亿',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: 'AI宠物短剧创作者',
    authorFollowers: 350000,
    views: 190000000,
    likes: 6500000,
    comments: 320000,
    shares: 480000,
    duration: 60,
    date: '2025-07-01',
    tags: ['AI宠物短剧', '胖橘猫', '拟人化', '连载103集', '累计破亿', '宫斗', '云吸宠'],
    script: '《胖橘的故事》更新至103集，累计播放量突破1.9亿。AI宠物短剧在2025年迎来爆发式增长，带有"AI宠物"标签的内容播放量在30天内暴增420%，话题#AI宠物挑战累计播放量高达16.8亿次。与简单的"穿衣戴帽配音"不同，如今的AI宠物短剧让AI技术深度赋能萌宠，将它们打造成能精准演绎喜怒哀乐的"专业演员"，用科技重新定义宠物视频的边界。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2026-07-30 QQ新闻报道'
  },
  {
    id: 'auto013',
    title: 'AI小比熊守护婴儿一整天：73万转发45.2万点赞引爆全网',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: '玉面小比熊',
    authorFollowers: 800000,
    views: 50000000,
    likes: 452000,
    comments: 61000,
    shares: 730000,
    duration: 45,
    date: '2025-06-20',
    tags: ['AI宠物', '小比熊', '守护婴儿', '暖心', '73万转发', '全网爆火', '拟人化'],
    script: '一段由AI生成的"小比熊守护婴儿一整天"的短视频在全网爆火，这只"尽职尽责"的虚拟萌宠收获了73万转发、45.2万点赞，引发6.1万条暖心评论。AI宠物短剧正以惊人速度席卷抖音、快手、小红书等平台。与《霸总雪纳瑞爱上我》《比熊殿下她权倾天下》《橘猫复仇记》等系列一起，掀起了"云吸宠"的新浪潮。AI语音合成让宠物能"开口说话"，表情动作模拟技术则让毛孩子们可以完成拟人化表演。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2026-07-30 QQ新闻报道'
  },
  {
    id: 'auto014',
    title: '《749秘档：秦岭邪雨》AI短剧：24小时播放破2000万付费近6万',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: '探云AI',
    authorFollowers: 150000,
    views: 50000000,
    likes: 2500000,
    comments: 120000,
    shares: 180000,
    duration: 120,
    date: '2025-12-05',
    tags: ['AI短剧', '749秘档', '悬疑探险', '秦岭', '付费短剧', '24小时破千万', '探云AI'],
    script: '由探云AI创作的《749秘档：秦岭邪雨》24小时播放量突破2000万，付费人数接近6万。虽然细看之下也有老龙王口型对不上的问题，但丝毫不影响观众付费热情，上线一周原生端付费就达52万。这部剧代表了AI短剧从免费观看向付费模式的转型，证明了优质AI内容能够直接产生商业价值。题材上融合了悬疑探险与中式怪谈，精准击中下沉市场用户的猎奇需求。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2026-07-30 今日头条报道'
  },
  {
    id: 'auto015',
    title: '《Fruit Love Island》AI水果恋综：TikTok 10天狂揽3亿播放',
    platform: 'tiktok',
    categoryId: 'aigc_create',
    author: '@ai.cinema021',
    authorFollowers: 3100000,
    views: 300000000,
    likes: 12000000,
    comments: 600000,
    shares: 900000,
    duration: 60,
    date: '2025-05-15',
    tags: ['AI短剧', '水果恋综', 'TikTok', '狗血剧情', '全球爆款', '9天涨粉310万', '跨文化'],
    script: 'TikTok账号@ai.cinema021推出的AI水果恋综《Fruit Love Island》，9天内粉丝暴涨超310万，21集平均每集观看量超1000万，10天狂揽3亿播放。香蕉男与草莓女在豪华别墅里狗血开撕的剧情，越过了语言和文化的边界，在全球社交媒体引发疯狂传播。AI宠物剧、水果狗血剧等内容正以不可控的速度席卷全球短视频平台。新一代AI工具如Seedance 2.0、可灵AI、即梦等，已让AI生成的角色在情绪表达上逼近真人演员水准。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2026-07-30 QQ新闻报道'
  },
  {
    id: 'auto016',
    title: '《魅魔叛主，我反手养成八翼炽天使》AI漫剧：播放量1.52亿',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: 'AI漫剧创作者',
    authorFollowers: 120000,
    views: 152000000,
    likes: 5800000,
    comments: 280000,
    shares: 420000,
    duration: 120,
    date: '2025-11-20',
    tags: ['AI漫剧', '御兽修仙', '进阶爽感', '垂直题材', '播放量破亿', '男频'],
    script: '《魅魔叛主，我反手养成八翼炽天使》聚焦御兽修仙设定，以"培育最强天使"的进阶爽感拿下1.52亿播放量。AI漫剧更注重"垂直题材深耕"，玄幻修仙题材占比高达39%，且多围绕细分世界观展开。与AI真人短剧的"泛题材融合"不同，AI漫剧凭借2D制作难度较低、不存在肤色肌理和真人光照等复杂视效的优势，可以用夸张的方式呈现剧情和人物，这也是AI漫剧"井喷"的原因之一。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2026-07-30 虎嗅报道'
  },
  {
    id: 'auto017',
    title: '《AI猫咪演绎人生系列》：127集累计播放量超4.5亿',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: 'AI宠物短剧创作者',
    authorFollowers: 500000,
    views: 450000000,
    likes: 15000000,
    comments: 750000,
    shares: 1100000,
    duration: 60,
    date: '2025-07-10',
    tags: ['AI宠物短剧', '猫咪拟人化', '连载127集', '累计4.5亿', '抖音最高播放', '云吸宠', '情感共鸣'],
    script: '《AI猫咪演绎人生系列》更新至127集，播放量超过4.5亿，是2025年抖音播放量最高的AI宠物短剧系列。从《神猫奶爸》开创AI宠物短剧先河，到《胖橘的故事》《AI猫咪演绎人生系列》的爆发，AI宠物短剧已经完全突破传统宠物视频的局限，不再是简单卖萌，而是能够承载复杂情感和剧情的"微缩人生"。AI语音合成让宠物能"开口说话"并实现个性化声线定制，表情动作模拟技术则让毛孩子们完成拟人化的精彩表演，从"宠物"华丽转身为"专业演员"。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2026-07-30 QQ新闻报道'
  },

  /* ======== 2026年下半年最新全网爆款（WebSearch搜索 2026-09-03） ======== */
  {
    id: 'auto018',
    title: '《百匠:纸契灵》AI国风短片：福州草台班子13天手搓7000万播放',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: '万梦生团队',
    authorFollowers: 580000,
    views: 70000000,
    likes: 4000000,
    comments: 185000,
    shares: 290000,
    duration: 480,
    date: '2026-07-15',
    tags: ['AI短片', '国风赛博', '剪纸文化', '13天手搓', '福州草台班子', '万梦生', '7000万播放'],
    script: '由福州"草台班子"万梦生团队（赵万权+阿生+瓜铭）创作的8分钟AI短片《百匠:纸契灵》，发布48小时内播放量突破5000万，截至目前已超7000万，点赞突破400万。灵感源于福建剪纸文化，将红军形象与剪纸元素结合。三人非科班出身：赵万权做过7年搬运工、阿生是水果店主、瓜铭是前灯光师。今年初才凑到一起，全部使用即梦AI+国产工具，1万元算力成本，13天完成。网友直呼"夯爆了"，评价"该片重新定位了国风赛博打斗"，河北网友惊叹"这要做成电影不知道能有多火"。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2026-09-03 澎湃新闻报道'
  },
  {
    id: 'auto019',
    title: '《流金谷恩仇录》央视网AI奇谈：全网破6000万 单平台转发144.6万',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: '央视网《AI奇谈》',
    authorFollowers: 3200000,
    views: 60000000,
    likes: 5800000,
    comments: 280000,
    shares: 1446000,
    duration: 320,
    date: '2026-03-18',
    tags: ['央视网', 'AI奇谈', '武侠寓言', '国家队AI', '止戈为武', '跨海破圈', 'AI漫剧'],
    script: '央视网原创AIGC栏目《AI奇谈》推出的5分钟武侠寓言动画《止戈为武:流金谷无"鹰"家》（网友称《流金谷恩仇录》），用武侠寓言形式解构中东地缘政治、美元石油霸权与全球反霸权主题。3月18日上线当日空降抖音热点榜TOP3，单条播放破3200万，10小时点赞破百万，全网播放破6000万。知乎热榜TOP1（热度3500万）、B站TOP3。抖音单平台转发144.6万次。影片热度跨越海峡，火到台湾地区及X平台，台湾节目评论称"连小朋友都能看懂"。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2026-09-03 央视网官方报道'
  },
  {
    id: 'auto020',
    title: '《中式天庭》34秒纯视觉AI短片：4天500万播放 #ChineseHeaven刷屏',
    platform: 'tiktok',
    categoryId: 'aigc_create',
    author: '栖光',
    authorFollowers: 380000,
    views: 5000000,
    likes: 3000000,
    comments: 45000,
    shares: 280000,
    duration: 34,
    date: '2026-08-08',
    tags: ['中式天庭', 'ChineseHeaven', '巨物美学', '国画留白', '纯视觉', '零语言', '爆款刷屏'],
    script: '34秒视频，没剧情、没台词，只有白玉长廊、云海仙宫、南天门、衣带飘飘的人影。被搬运到TikTok和X后，4天播放破500万，点赞超300万，#ChineseHeaven 刷屏。创作者"栖光"是1991年生的浙江眼镜店老板，AI视频是自学两年的副业。单条制作耗时5小时，1080P规格AI付费成本30-40元，要求高反复调整约100元。工具用即梦AI、可灵、海螺、Vidu等国产栈，无海外Sora/Runway依赖。横向对比传统国风30秒短片实拍+建模+渲染+后期动辄几千到几万起，AI把"能生成"推进到"能稳定做完一条成片"，成本差了两个数量级。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2026-09-03 今日头条报道'
  },
  {
    id: 'auto021',
    title: '《万物生》AI系列短片：前两集累计播放近1亿 涨粉百万',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: '命比梦长',
    authorFollowers: 1000000,
    views: 95000000,
    likes: 6000000,
    comments: 320000,
    shares: 450000,
    duration: 600,
    date: '2026-07-20',
    tags: ['AI系列短片', '机械文明', '修真体系', '世界观', '连载', '第一集300万赞'],
    script: '抖音账号"命比梦长"推出的《万物生》，不再是一段单纯追求奇观的AI视频，而是一部拥有机械文明、超自然生物和修真体系的系列短片。第一集时长达到10分钟，获得超过300万点赞；前两集累计播放量接近1亿，账号粉丝增长至百万级。这是中国AIGC头部超创从"展示模型能力"转向"创造连续内容"的代表案例。与早期AIGC视频相比，这些作品虽然仍然依靠巨型生物、城市异变和末日景观吸引用户，但已经拥有相对稳定的世界观、角色和故事悬念。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2026-09-03 36氪报道'
  },
  {
    id: 'auto022',
    title: '《潜入梦海》AI短片：上海国际电影节AIGC单元最佳创意奖',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: '刘璨闻团队',
    authorFollowers: 220000,
    views: 12000000,
    likes: 850000,
    comments: 38000,
    shares: 56000,
    duration: 480,
    date: '2026-05-10',
    tags: ['AI短片', '上海电影节', 'AIGC单元', '最佳创意奖', '00后创作者', '4人团队'],
    script: '00后创作者刘璨闻参与制作的《潜入梦海》，由4人团队完成，时长8分钟，包含大巴爆炸和异国场景等传统制作中的高成本画面。影片AI软件成本不到5000元，制作周期约一周，并获得上海国际电影节AIGC单元最佳创意奖。影视型超创的典型案例——使用AI完成结构完整的影像作品，目标不是生产几秒钟的爆款。AI软件成本不到5000元，制作周期约一周，证明AI可以让个人和小团队完成传统上需要大投资的影像作品。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2026-09-03 36氪报道'
  },
  {
    id: 'auto023',
    title: '《Everything Grows》中国机械朋克AI剧：TikTok 7500万播放',
    platform: 'tiktok',
    categoryId: 'aigc_create',
    author: '@Mibimengchang',
    authorFollowers: 850000,
    views: 75000000,
    likes: 4500000,
    comments: 180000,
    shares: 280000,
    duration: 600,
    date: '2026-05-17',
    tags: ['中国机械朋克', 'Chinese Mecha-Punk', 'TikTok', 'AI短剧', '道家穿越', '世界观'],
    script: '《Everything Grows》由创作者"Mibimengchang"团队打造，因独特的"中国机械朋克"（Chinese Mecha-Punk）世界观构建引发广泛关注。第一集5月17日发布，播放量突破6000万；6月8日上线的第二集迅速突破1500万，累计播放量超过7500万。故事讲述一位现代道士穿越到一个机械与修炼共存的虚构中国古代王朝。其电影级视觉效果、高饱和度的美术风格，以及专业团队合作（使用飞书进行项目协作和分工）是其成功的关键。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2026-09-03 Houdao AI报道'
  },
  {
    id: 'auto024',
    title: '《古风诗人流放》AI短片：李白苏轼五诗人 TikTok 6500万播放422万点赞',
    platform: 'tiktok',
    categoryId: 'aigc_create',
    author: '@DirectorLiRang',
    authorFollowers: 720000,
    views: 65000000,
    likes: 4220000,
    comments: 156000,
    shares: 320000,
    duration: 180,
    date: '2026-06-08',
    tags: ['古风诗人', '李白苏轼', '流放', 'TikTok', '文化出海', '422万点赞'],
    script: 'TikTok创作者"Director Li Rang"用AI重现了李白、苏轼等五位著名中国古代诗人在流放时期的场景，结合他们千古流传的诗句。视频因其丰富的古典美学和深刻的情感内涵引起强烈共鸣，TikTok播放量突破6500万，点赞422万。证明AI能够将抽象的文学意象和历史时刻转化为有形的视听体验，极大增强文化内容的情感冲击力，是AI出海传播传统文化的优秀案例。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2026-09-03 Houdao AI报道'
  },
  {
    id: 'auto025',
    title: '《斩仙台AI真人版》里程碑：12人30天10万元 累计播放1.9亿',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: '妙想制片厂x可梦AI',
    authorFollowers: 850000,
    views: 190000000,
    likes: 9500000,
    comments: 420000,
    shares: 680000,
    duration: 720,
    date: '2026-01-15',
    tags: ['AI真人版', '斩仙台', '12人团队', '10万元算力', '30天', '破圈标志', '累计1.9亿'],
    script: '《斩仙台AI真人版》作为2026年初上线的AI真人剧里程碑作品，在成本、视觉质量、制作周期方面实现标志性突破。由12人团队以10万元算力成本、30天周期制作完成，上线6天播放量即破亿，累计超1.9亿。作品在面部一致性、远景清晰度、电影级特效转场等方面表现惊艳，还能快速生成御剑、斗法等复杂动作帧，规避真人拍摄的安全风险与动作局限。被业内称为2026年AI仿真人短剧的"破圈"标志。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2026-09-03 ima.qq.com/澎湃新闻'
  },
  {
    id: 'auto026',
    title: '《风水天师》唐季礼监制AI漫剧：第一季12小时破亿 总播放6亿',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: '江西时刻互动',
    authorFollowers: 1200000,
    views: 600000000,
    likes: 18000000,
    comments: 850000,
    shares: 1200000,
    duration: 1100,
    date: '2026-03-25',
    tags: ['AI漫剧', '风水天师', '唐季礼', '江西时刻互动', '12小时破亿', '总6亿', '现象级'],
    script: '由国际知名导演唐季礼担任总监制，赣江新区微短剧企业江西时刻互动制作出品的AI仿真人动漫短剧《风水天师》。改编自热门小说《民间风水师笔记》，讲述风水传人李乘风悬壶济世、惩恶扬善、守护华夏龙脉的故事，共计61集、总时长超180分钟。第一季上线12小时播放量破亿，总播放量突破6亿纪录；第二季上线次日便冲入DataEye抖音动态漫热播榜前列，热度值超5000万，收藏过10万+。AI短剧从"粗放式"量产向工业化、精品化创作转型。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2026-09-03 江西赣江新区/澎湃新闻'
  },
  {
    id: 'auto027',
    title: '《7天拿下AI视频创作:零基础全流程》抖音19.9万赞 19.8万收藏',
    platform: 'douyin',
    categoryId: 'aigc',
    author: 'AI培训达人',
    authorFollowers: 480000,
    views: 5600000,
    likes: 199000,
    comments: 46000,
    shares: 43000,
    duration: 480,
    date: '2026-08-20',
    tags: ['AI视频创作', '7天速成', '零基础', '保姆级教程', '19.9万赞', '19.8万收藏', '爆款公式'],
    script: '一条培训视频为什么能获得近20万次收藏？真正驱动传播的，往往不是"AI风口"四个字，而是结果展示、确定性承诺和可执行路径的组合。《7天拿下AI视频创作:零基础全流程》课程：19.9万赞|4.6万评论|19.8万收藏|4.3万分享。爆点：7天速成、零基础、完整路径、资料诱饵。课程内容覆盖AI脚本、智能分镜、实拍增强、自动剪辑，适配新闻、短剧、文旅、政务、电商等场景。Codex拆解高收藏视频的共性，反向生成可直接拍摄的60秒脚本，是AIGC培训赛道的爆款公式。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2026-09-03 搜狐报道'
  },

  /* ======== 2026年9月最新全网爆款（WebSearch搜索 2026-09-04） ======== */
  {
    id: 'auto028',
    title: '《东北山野诡事》AI短剧：上线24小时破1000万播放，打破圈层获白领青睐',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: '上海探云AI团队',
    authorFollowers: 150000,
    views: 10000000,
    likes: 2500000,
    comments: 120000,
    shares: 180000,
    duration: 900,
    date: '2025-11-20',
    tags: ['AI短剧', '东北民俗', '悬疑探险', '电影质感', '破圈', '白领受众'],
    script: '国产电影级AIGC竖屏短剧《东北山野诡事》上线即引爆网络。融合奇幻、悬疑、冒险等元素，通过"亲情守护+家国大义"的双线叙事，构建起兼具电影质感与民族精神内核的视听盛宴。上线24小时突破1000万播放量，打破以往短剧用户画像局限，收获大量都市白领关注，男女观众占比几近持平。出品方上海探云AI团队通过优化多模态大模型，实现镜头语言自然度及丰富度升级，证明AIGC不仅能造景造物，也能服务更深层的叙事构建与价值表达。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2026-09-04  southfi财经网报道'
  },
  {
    id: 'auto029',
    title: '60秒做出60W赞哲学视频！DeepSeek+即梦AI保姆级教程',
    platform: 'wechat',
    categoryId: 'aigc',
    author: 'AI创变工坊·桑榆',
    authorFollowers: 85000,
    views: 5000000,
    likes: 600000,
    comments: 45000,
    shares: 120000,
    duration: 60,
    date: '2025-06-12',
    tags: ['DeepSeek', '即梦AI', '哲学视频', '60万赞', '保姆级教程', '小白当天收益'],
    script: '最近一条"凡事发生皆有利于我"的哲学视频横扫抖音，单条点赞60W+，评论区万人共鸣。更惊人的是，这类视频用AI制作只要3步5分钟，新手也能轻松复刻爆款！核心密码：人性拿捏精准——"孤独是顶级自由""过度清醒是灾难"等文案直击现代人焦虑；视觉冲击力强——通过DeepSeek生成"金漆修补青瓷""暴雨竹林"等意象，搭配即梦AI的中式水墨风，自带高级禅意滤镜。变现空间极大：橱窗带货国学书籍/手串/茶具（佣金30%-70%）、私域暴利易经课程/手写心经（客单价500+）、收徒教学教剪辑变现（定价199-1980元）。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2026-09-04  ima.qq.com/微信文章'
  },
  {
    id: 'auto030',
    title: '只用3款免费AI工具，做出10w+爆款短视频',
    platform: 'toutiao',
    categoryId: 'aigc',
    author: '智趣AI日常',
    authorFollowers: 120000,
    views: 2000000,
    likes: 73000,
    comments: 8500,
    shares: 15000,
    duration: 180,
    date: '2025-12-30',
    tags: ['免费AI工具', 'ChatGPT', 'CapCut', '剪映', '10w+爆款', '35分钟出片'],
    script: '作者花了35分钟，用3个完全免费的AI工具，做出一条点赞7.3w、涨粉1.2w的短视频，并且当天带货佣金到账527元。工具清单：①ChatGPT国内镜像（免费4o/30次/天）②CapCut「AI漫画」模板（官方限免）③剪映「图文一键成片」+自动配音。实操流程：0-5分钟找爆款选题（抖音热点宝→搜索"AI漫画重生"→按"低粉爆款"排序）→5-15分钟ChatGPT写反转脚本→15-25分钟AI漫画生成→25-30分钟剪映一键成片→30-35分钟发布设置。流量密码：封面加3D字体"杀疯了"点击率↑42%；第1秒加"耳机党福利"字幕完播率↑18%；评论区置顶"想要后续扣1"互动率↑35%。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2026-09-04  今日头条报道'
  },
  {
    id: 'auto031',
    title: '傻瓜式爆款攻略！DeepSeek+即梦AI图文转视频，手机3步出片',
    platform: 'toutiao',
    categoryId: 'aigc',
    author: '摸鱼王',
    authorFollowers: 95000,
    views: 1800000,
    likes: 52000,
    comments: 6800,
    shares: 12000,
    duration: 240,
    date: '2025-03-14',
    tags: ['DeepSeek', '即梦AI', '图文转视频', '手机3步', '傻瓜式', '小白友好'],
    script: '全程不用写代码，手机端即可完成。必装APP：DeepSeek（微信小程序直接使用）、即梦AI（应用商店下载，抖音账号一键登录）、剪映（基础免费功能即可）。手机3步出片法：第一步用DeepSeek生成文案+图片描述（输入"帮我写一个30秒的广告文案"→点击"优化文案"→选择风格→生成图片描述）；第二步即梦AI一键生成视频（打开APP点击"图文转视频"→粘贴文案和图片描述→点击"智能分镜"→设置视频比例和主播声音→生成预览）；第三步剪映流量密码优化（导入视频→点击"一键成片"→添加前3秒"手机震动+叮铃音效"→智能字幕同步→结尾叠加"立即购买"弹窗）。附赠美食账号、书单号等小白必存模板库。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2026-09-04  今日头条报道'
  },
  {
    id: 'auto032',
    title: '《斩仙台AI真人版》里程碑：6天播放破亿，AI真人短剧正式破圈',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: '妙想制片厂x可梦AI',
    authorFollowers: 850000,
    views: 172000000,
    likes: 85000,
    comments: 42000,
    shares: 68000,
    duration: 720,
    date: '2025-12-15',
    tags: ['AI真人版', '斩仙台', '6天破亿', '破圈标志', '精品化', '工业化'],
    script: '2025年底现象级AI真人短剧《斩仙台AI真人版》横空出世。上线仅48小时即登顶红果漫剧热播榜TOP1，6天全网总播放量突破1亿大关；截至1月23日，抖音单平台播放量达1.72亿。首集获赞8.5万，次集留存率高达76%，评论区高频出现"比真人演得还真""连睫毛颤动都像活的"等真实观感反馈。系统性攻克了AI真人短剧三大硬伤：人物面部一致性差、中远景镜头失真、表情微动僵硬。特效质感逼近院线标准——云海翻涌的斩仙台、金箍棒挥出的粒子光效、甚至角色流泪时泪珠折射的环境光，均经得起逐帧审视。业内资深制片人评价："它让观众第一次忘了在看AI生成。"',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2026-09-04  AI部落报道'
  },
  {
    id: 'auto033',
    title: 'AI短剧2025年市场规模突破120亿元：13部播放量破亿',
    platform: 'toutiao',
    categoryId: 'aigc_create',
    author: '文汇报/网易',
    authorFollowers: 500000,
    views: 5000000,
    likes: 85000,
    comments: 12000,
    shares: 22000,
    duration: 300,
    date: '2025-12-28',
    tags: ['AI短剧', '市场规模', '120亿元', '13部破亿', '资本追逐', '行业报告'],
    script: '2025年AI短剧迎来关键性增长节点。据文汇报报道，全年达到千万播放量的AI仿真人短剧已有37部，播放量在3500万以上的AI漫剧已有22部。在统计的59部作品中，有13部播放量破亿，4部为AI真人短剧、9部为AI漫剧。《奶团太后宫心计》以2.2亿播放量拔得头筹；《洪荒：代管截教，忽悠出了一堆圣人》以2.71亿播放量占得AI漫剧榜首。DataEye监测显示：抖音11月上榜AI短剧达217部，较年初增长50倍。AI真人短剧市场规模已明确突破120亿元，同比增长超300%，供给量较去年年初暴涨50倍。精品级AI真人短剧制作成本已压缩至约1000元/分钟，80分钟成片总成本不足传统实拍的1/10。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2026-09-04  网易/文汇报报道'
  },
  {
    id: 'auto034',
    title: 'DeepSeek+即梦AI高效制作养生视频：强强联合爆款教程',
    platform: 'toutiao',
    categoryId: 'aigc',
    author: '腾讯云开发者社区',
    authorFollowers: 280000,
    views: 1200000,
    likes: 28000,
    comments: 3200,
    shares: 8500,
    duration: 300,
    date: '2025-08-15',
    tags: ['DeepSeek', '即梦AI', '养生视频', '爆款教程', '中医养生', '分镜脚本'],
    script: 'AI技术让健康养生赛道视频制作越来越简单，很多创作者仅凭AI工具制作的养生视频就能获得数十万播放量，甚至有些账号短时间内就能涨粉几十万。教程详解：第一步用DeepSeek生成养生文案（打开DeepSeek进入深度思考模式→输入"我想制作一个关于中医养生的AI视频，请参考以下两个爆款短视频养生文案，帮我生成5条养生视频文案"→挑选最符合需求的内容）；第二步生成绘画提示词（输入"请根据Midjourney语法规则优化详细分镜脚本，包含画面细节、风格参数与镜头语言，生成8个分镜头的提示词"）；第三步用即梦AI生成图片（选择"图片2.0pro"模型，比率9:16→输入分镜提示词→挑选合适图片点击"超清HD"导出）。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2026-09-04  腾讯云开发者社区'
  },
  {
    id: 'auto035',
    title: '《兴安岭诡事》国内首部付费AI短剧：21小时破千万播放，收益超30万',
    platform: 'douyin',
    categoryId: 'aigc_create',
    author: '杭州炬核智能科技',
    authorFollowers: 120000,
    views: 5613000,
    likes: 85000,
    comments: 12000,
    shares: 22000,
    duration: 600,
    date: '2025-02-15',
    tags: ['AI短剧', '付费模式', '兴安岭', '21小时破千万', '首部付费', '收益30万'],
    script: '国内首部付费AI短剧《兴安岭诡事》由5位AIGC艺术家用时3个月完成，90%场景使用AI生成。上线后不到21小时便突破千万播放，上线9天播放量超过4000万。以5.9元11集的付费模式，收获超30万元的收入，账号涨粉10万+。虽然角色面部表情处理较为牵强、多人物出镜时缺乏交流感、画面剪辑大量采用跳切导致衔接不流畅，但作为2025年初的AI短剧试水作品，其商业验证意义重大。仅仅一年后，AI视频生成技术能力已得到极大提升，字节跳动旗下即梦AI正式上线Seedance 2.0版本，视频生成可用率已提升至90%以上。',
    videoUrl: '',
    isReal: true,
    source: 'WebSearch搜索 2026-09-04  DoNews/ima.qq.com报道'
  }
];

/* 爆款直播示例数据 */
const DEMO_STREAMS = [
  {
    id: 's001',
    title: 'AI工具专场：40+款工具一次讲透',
    platform: 'douyin',
    host: 'AI实战派小林',
    categoryId: 'aigc',
    peakViewers: 86000,
    avgViewers: 32000,
    duration: 186,
    sales: 128000,
    orders: 2400,
    gmv: 128000,
    date: '2026-07-26',
    highlights: ['开场5分钟在线破8万', 'AI课程链接转化率12%', '评论区互动率8.5%'],
    tags: ['AI培训', '课程带货', '知识付费']
  },
  {
    id: 's002',
    title: '夏季清仓大促：女装专场',
    platform: 'douyin',
    host: '带货一姐小美',
    categoryId: 'ecommerce',
    peakViewers: 156000,
    avgViewers: 78000,
    duration: 210,
    sales: 86000,
    orders: 18500,
    gmv: 580000,
    date: '2026-07-27',
    highlights: ['开场即爆，峰值15.6万', '利润款转化率9.2%', '返场3次均秒空'],
    tags: ['女装', '清仓', '大促']
  },
  {
    id: 's003',
    title: 'Midjourney零基础到精通直播课',
    platform: 'bilibili',
    host: '设计老王AI课',
    categoryId: 'aigc',
    peakViewers: 42000,
    avgViewers: 18000,
    duration: 165,
    sales: 3200,
    orders: 890,
    gmv: 96000,
    date: '2026-07-25',
    highlights: ['免费试听引流转化21%', '弹幕互动量2.4万', '课程续费率45%'],
    tags: ['Midjourney', '设计培训', 'B站直播']
  },
  {
    id: 's004',
    title: '新手做自媒体第1天：从0到1全流程',
    platform: 'wechat',
    host: '自媒体老张',
    categoryId: 'knowledge',
    peakViewers: 68000,
    avgViewers: 35000,
    duration: 140,
    sales: 5600,
    orders: 1200,
    gmv: 89000,
    date: '2026-07-24',
    highlights: ['视频号推荐流量占比62%', '中年用户群体精准', '付费转化路径极短'],
    tags: ['自媒体', '新手起号', '视频号']
  }
];

/* 爆款元素标签 */
const VIRAL_ELEMENTS = [
  { id: 'pain',      name: '痛点刺激',  icon: '😰', desc: '开头直击用户核心痛点，让人无法划走' },
  { id: 'suspense',  name: '悬念设置',  icon: '🤔', desc: '制造信息缺口，激发好奇心，制造期待' },
  { id: 'data',      name: '数据冲击',  icon: '📊', desc: '用具体数字制造冲击感，增强可信度' },
  { id: 'emotion',   name: '情感共鸣',  icon: '❤️', desc: '唤起用户情感认同，产生转发冲动' },
  { id: 'conflict',  name: '争议对立',  icon: '⚡', desc: '制造反共识观点，引发评论区讨论' },
  { id: 'value',     name: '干货清单',  icon: '📝', desc: '提供明确可执行的价值，触发收藏' },
  { id: 'story',     name: '故事代入',  icon: '📖', desc: '用真实故事拉近距离，增强代入感' },
  { id: 'authority', name: '权威背书',  icon: '🏆', desc: '借助数据/案例/身份建立信任' }
];

/* 平台爆款逻辑 */
const PLATFORM_LOGIC = {
  douyin: {
    name: '抖音爆款逻辑',
    rules: [
      '前3秒必须爆：要么痛点，要么反差，要么悬念',
      '完播率是第一指标：节奏快，信息密度高，不废话',
      '短句为主：每句不超过15字，制造紧凑感',
      '评论区引导：结尾留钩子，引导互动',
      '黄金时间轴：0-3s钩子 → 3-15s铺垫 → 15-30s转折 → 30-50s价值 → 50-60sCTA',
      '口语化：说人话，不说书面语，不用复杂句式'
    ]
  },
  xhs: {
    name: '小红书爆款逻辑',
    rules: [
      '种草感第一：不是卖货，是分享体验',
      'emoji丰富：每段至少1-2个emoji，视觉节奏感',
      '"姐妹们"开头：建立亲近感，降低防备心',
      '具体场景化：描述要具体到画面，不要笼统',
      '标题党但有料：标题吸引人，内容要有干货支撑',
      '标签矩阵：3-5个话题标签，覆盖搜索流量'
    ]
  },
  bilibili: {
    name: 'B站爆款逻辑',
    rules: [
      '信息密度极高：UP主要给干货，不能水',
      '逻辑递进：有起承转合，不是碎片信息堆砌',
      '弹幕梗：适当玩梗，制造弹幕互动点',
      '时长3-10分钟最佳：太短信息不够，太长完播低',
      '观众老爷心态：尊重观众智商，不教条',
      '分区适配：不同分区有不同的内容偏好'
    ]
  },
  kuaishou: {
    name: '快手爆款逻辑',
    rules: [
      '老铁文化：真实、接地气、有人情味',
      '信任经济：人设比内容更重要',
      '直接说事：不绕弯子，开头就说重点',
      '接地气场景：生活化场景，不要精致布景',
      '互动感强：经常喊话老铁，制造参与感'
    ]
  },
  wechat: {
    name: '视频号爆款逻辑',
    rules: [
      '中年受众为主：内容偏价值观、人生感悟',
      '金句感：每条要有1-2句能截图转发的金句',
      '社交推荐制：转发到朋友圈是核心传播路径',
      '信息增量：不能只是观点，要有新信息或新角度',
      '情绪正向：正能量、鸡汤类内容传播力更强'
    ]
  },
  toutiao: {
    name: '今日头条爆款逻辑',
    rules: [
      '标题决定生死：信息量大+悬念+数字',
      '深度内容优先：长文/长视频权重更高',
      '关键词覆盖：标题和正文覆盖搜索热词',
      '时效性：追热点、追时效的内容权重高',
      '互动率：评论和转发是重要推荐指标'
    ]
  }
};

/* 内容来源说明 */
const DATA_SOURCE_INFO = {
  lastUpdate: '2026-09-04',
  totalVideos: 65,
  realVideos: 59,
  demoVideos: 6,
  sources: [
    '新榜数据（new.qq.com）- AI爆款盘点报告',
    'B站公开播放数据',
    '今日头条公开文章',
    'QQ新闻公开报道',
    '58课堂教程信息',
    '猎人社课程信息',
    '新浪科技报道',
    '百家号公开报道',
    'WebSearch全网搜索',
    '平台公开信息整理'
  ],
  limitations: [
    '抖音、快手、小红书等平台无公开内容搜索API',
    '无法自动实时爬取平台数据（反爬机制）',
    '当前数据为人工整理的公开报道信息',
    '如需实时更新，需接入第三方数据服务商API'
  ],
  updateGuide: '系统每日自动搜索全网爆款视频并更新。如需手动添加，请在应用内「内容更新中心」添加，或联系开发者批量导入'
};
